// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoverInfo.proto

package com.douyin.webcast;

public final class CoverInfoSerializer {
  private CoverInfoSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CoverInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.CoverInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string url_list = 1;</code>
     * @return A list containing the urlList.
     */
    java.util.List<java.lang.String>
        getUrlListList();
    /**
     * <code>repeated string url_list = 1;</code>
     * @return The count of urlList.
     */
    int getUrlListCount();
    /**
     * <code>repeated string url_list = 1;</code>
     * @param index The index of the element to return.
     * @return The urlList at the given index.
     */
    java.lang.String getUrlList(int index);
    /**
     * <code>repeated string url_list = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the urlList at the given index.
     */
    com.google.protobuf.ByteString
        getUrlListBytes(int index);

    /**
     * <code>string uri = 2;</code>
     * @return The uri.
     */
    java.lang.String getUri();
    /**
     * <code>string uri = 2;</code>
     * @return The bytes for uri.
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <code>int32 width = 4;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>string avg_color = 5;</code>
     * @return The avgColor.
     */
    java.lang.String getAvgColor();
    /**
     * <code>string avg_color = 5;</code>
     * @return The bytes for avgColor.
     */
    com.google.protobuf.ByteString
        getAvgColorBytes();

    /**
     * <code>int32 image_type = 6;</code>
     * @return The imageType.
     */
    int getImageType();

    /**
     * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
     * @return Whether the colorInfo field is set.
     */
    boolean hasColorInfo();
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
     * @return The colorInfo.
     */
    com.douyin.webcast.ColorInfoSerializer.ColorInfo getColorInfo();
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
     */
    com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder getColorInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.douyin.webcast.proto.CoverInfo}
   */
  public static final class CoverInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.CoverInfo)
      CoverInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CoverInfo.newBuilder() to construct.
    private CoverInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CoverInfo() {
      urlList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      uri_ = "";
      avgColor_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CoverInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CoverInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                urlList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              urlList_.add(s);
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 24: {

              height_ = input.readInt32();
              break;
            }
            case 32: {

              width_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              avgColor_ = s;
              break;
            }
            case 48: {

              imageType_ = input.readInt32();
              break;
            }
            case 66: {
              com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder subBuilder = null;
              if (colorInfo_ != null) {
                subBuilder = colorInfo_.toBuilder();
              }
              colorInfo_ = input.readMessage(com.douyin.webcast.ColorInfoSerializer.ColorInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(colorInfo_);
                colorInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          urlList_ = urlList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.douyin.webcast.CoverInfoSerializer.internal_static_com_douyin_webcast_proto_CoverInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.douyin.webcast.CoverInfoSerializer.internal_static_com_douyin_webcast_proto_CoverInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.douyin.webcast.CoverInfoSerializer.CoverInfo.class, com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder.class);
    }

    public static final int URL_LIST_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList urlList_;
    /**
     * <code>repeated string url_list = 1;</code>
     * @return A list containing the urlList.
     */
    public com.google.protobuf.ProtocolStringList
        getUrlListList() {
      return urlList_;
    }
    /**
     * <code>repeated string url_list = 1;</code>
     * @return The count of urlList.
     */
    public int getUrlListCount() {
      return urlList_.size();
    }
    /**
     * <code>repeated string url_list = 1;</code>
     * @param index The index of the element to return.
     * @return The urlList at the given index.
     */
    public java.lang.String getUrlList(int index) {
      return urlList_.get(index);
    }
    /**
     * <code>repeated string url_list = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the urlList at the given index.
     */
    public com.google.protobuf.ByteString
        getUrlListBytes(int index) {
      return urlList_.getByteString(index);
    }

    public static final int URI_FIELD_NUMBER = 2;
    private volatile java.lang.Object uri_;
    /**
     * <code>string uri = 2;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <code>string uri = 2;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int WIDTH_FIELD_NUMBER = 4;
    private int width_;
    /**
     * <code>int32 width = 4;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int AVG_COLOR_FIELD_NUMBER = 5;
    private volatile java.lang.Object avgColor_;
    /**
     * <code>string avg_color = 5;</code>
     * @return The avgColor.
     */
    @java.lang.Override
    public java.lang.String getAvgColor() {
      java.lang.Object ref = avgColor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avgColor_ = s;
        return s;
      }
    }
    /**
     * <code>string avg_color = 5;</code>
     * @return The bytes for avgColor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAvgColorBytes() {
      java.lang.Object ref = avgColor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avgColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_TYPE_FIELD_NUMBER = 6;
    private int imageType_;
    /**
     * <code>int32 image_type = 6;</code>
     * @return The imageType.
     */
    @java.lang.Override
    public int getImageType() {
      return imageType_;
    }

    public static final int COLORINFO_FIELD_NUMBER = 8;
    private com.douyin.webcast.ColorInfoSerializer.ColorInfo colorInfo_;
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
     * @return Whether the colorInfo field is set.
     */
    @java.lang.Override
    public boolean hasColorInfo() {
      return colorInfo_ != null;
    }
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
     * @return The colorInfo.
     */
    @java.lang.Override
    public com.douyin.webcast.ColorInfoSerializer.ColorInfo getColorInfo() {
      return colorInfo_ == null ? com.douyin.webcast.ColorInfoSerializer.ColorInfo.getDefaultInstance() : colorInfo_;
    }
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder getColorInfoOrBuilder() {
      return getColorInfo();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < urlList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, urlList_.getRaw(i));
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uri_);
      }
      if (height_ != 0) {
        output.writeInt32(3, height_);
      }
      if (width_ != 0) {
        output.writeInt32(4, width_);
      }
      if (!getAvgColorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, avgColor_);
      }
      if (imageType_ != 0) {
        output.writeInt32(6, imageType_);
      }
      if (colorInfo_ != null) {
        output.writeMessage(8, getColorInfo());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < urlList_.size(); i++) {
          dataSize += computeStringSizeNoTag(urlList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUrlListList().size();
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uri_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, width_);
      }
      if (!getAvgColorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, avgColor_);
      }
      if (imageType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, imageType_);
      }
      if (colorInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getColorInfo());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.douyin.webcast.CoverInfoSerializer.CoverInfo)) {
        return super.equals(obj);
      }
      com.douyin.webcast.CoverInfoSerializer.CoverInfo other = (com.douyin.webcast.CoverInfoSerializer.CoverInfo) obj;

      if (!getUrlListList()
          .equals(other.getUrlListList())) return false;
      if (!getUri()
          .equals(other.getUri())) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getWidth()
          != other.getWidth()) return false;
      if (!getAvgColor()
          .equals(other.getAvgColor())) return false;
      if (getImageType()
          != other.getImageType()) return false;
      if (hasColorInfo() != other.hasColorInfo()) return false;
      if (hasColorInfo()) {
        if (!getColorInfo()
            .equals(other.getColorInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUrlListCount() > 0) {
        hash = (37 * hash) + URL_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getUrlListList().hashCode();
      }
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + AVG_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getAvgColor().hashCode();
      hash = (37 * hash) + IMAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getImageType();
      if (hasColorInfo()) {
        hash = (37 * hash) + COLORINFO_FIELD_NUMBER;
        hash = (53 * hash) + getColorInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.douyin.webcast.CoverInfoSerializer.CoverInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.CoverInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.CoverInfo)
        com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.CoverInfoSerializer.internal_static_com_douyin_webcast_proto_CoverInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.CoverInfoSerializer.internal_static_com_douyin_webcast_proto_CoverInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.CoverInfoSerializer.CoverInfo.class, com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder.class);
      }

      // Construct using com.douyin.webcast.CoverInfoSerializer.CoverInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        urlList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        uri_ = "";

        height_ = 0;

        width_ = 0;

        avgColor_ = "";

        imageType_ = 0;

        if (colorInfoBuilder_ == null) {
          colorInfo_ = null;
        } else {
          colorInfo_ = null;
          colorInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.douyin.webcast.CoverInfoSerializer.internal_static_com_douyin_webcast_proto_CoverInfo_descriptor;
      }

      @java.lang.Override
      public com.douyin.webcast.CoverInfoSerializer.CoverInfo getDefaultInstanceForType() {
        return com.douyin.webcast.CoverInfoSerializer.CoverInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.douyin.webcast.CoverInfoSerializer.CoverInfo build() {
        com.douyin.webcast.CoverInfoSerializer.CoverInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.douyin.webcast.CoverInfoSerializer.CoverInfo buildPartial() {
        com.douyin.webcast.CoverInfoSerializer.CoverInfo result = new com.douyin.webcast.CoverInfoSerializer.CoverInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          urlList_ = urlList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.urlList_ = urlList_;
        result.uri_ = uri_;
        result.height_ = height_;
        result.width_ = width_;
        result.avgColor_ = avgColor_;
        result.imageType_ = imageType_;
        if (colorInfoBuilder_ == null) {
          result.colorInfo_ = colorInfo_;
        } else {
          result.colorInfo_ = colorInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.douyin.webcast.CoverInfoSerializer.CoverInfo) {
          return mergeFrom((com.douyin.webcast.CoverInfoSerializer.CoverInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.douyin.webcast.CoverInfoSerializer.CoverInfo other) {
        if (other == com.douyin.webcast.CoverInfoSerializer.CoverInfo.getDefaultInstance()) return this;
        if (!other.urlList_.isEmpty()) {
          if (urlList_.isEmpty()) {
            urlList_ = other.urlList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUrlListIsMutable();
            urlList_.addAll(other.urlList_);
          }
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (!other.getAvgColor().isEmpty()) {
          avgColor_ = other.avgColor_;
          onChanged();
        }
        if (other.getImageType() != 0) {
          setImageType(other.getImageType());
        }
        if (other.hasColorInfo()) {
          mergeColorInfo(other.getColorInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.douyin.webcast.CoverInfoSerializer.CoverInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.douyin.webcast.CoverInfoSerializer.CoverInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList urlList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUrlListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          urlList_ = new com.google.protobuf.LazyStringArrayList(urlList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @return A list containing the urlList.
       */
      public com.google.protobuf.ProtocolStringList
          getUrlListList() {
        return urlList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @return The count of urlList.
       */
      public int getUrlListCount() {
        return urlList_.size();
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @param index The index of the element to return.
       * @return The urlList at the given index.
       */
      public java.lang.String getUrlList(int index) {
        return urlList_.get(index);
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the urlList at the given index.
       */
      public com.google.protobuf.ByteString
          getUrlListBytes(int index) {
        return urlList_.getByteString(index);
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @param index The index to set the value at.
       * @param value The urlList to set.
       * @return This builder for chaining.
       */
      public Builder setUrlList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlListIsMutable();
        urlList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @param value The urlList to add.
       * @return This builder for chaining.
       */
      public Builder addUrlList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUrlListIsMutable();
        urlList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @param values The urlList to add.
       * @return This builder for chaining.
       */
      public Builder addAllUrlList(
          java.lang.Iterable<java.lang.String> values) {
        ensureUrlListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, urlList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrlList() {
        urlList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string url_list = 1;</code>
       * @param value The bytes of the urlList to add.
       * @return This builder for chaining.
       */
      public Builder addUrlListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureUrlListIsMutable();
        urlList_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <code>string uri = 2;</code>
       * @return The uri.
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uri = 2;</code>
       * @return The bytes for uri.
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uri = 2;</code>
       * @param value The uri to set.
       * @return This builder for chaining.
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <code>string uri = 2;</code>
       * @param value The bytes for uri to set.
       * @return This builder for chaining.
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 3;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 4;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 4;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object avgColor_ = "";
      /**
       * <code>string avg_color = 5;</code>
       * @return The avgColor.
       */
      public java.lang.String getAvgColor() {
        java.lang.Object ref = avgColor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avgColor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string avg_color = 5;</code>
       * @return The bytes for avgColor.
       */
      public com.google.protobuf.ByteString
          getAvgColorBytes() {
        java.lang.Object ref = avgColor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avgColor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string avg_color = 5;</code>
       * @param value The avgColor to set.
       * @return This builder for chaining.
       */
      public Builder setAvgColor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avgColor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string avg_color = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvgColor() {
        
        avgColor_ = getDefaultInstance().getAvgColor();
        onChanged();
        return this;
      }
      /**
       * <code>string avg_color = 5;</code>
       * @param value The bytes for avgColor to set.
       * @return This builder for chaining.
       */
      public Builder setAvgColorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avgColor_ = value;
        onChanged();
        return this;
      }

      private int imageType_ ;
      /**
       * <code>int32 image_type = 6;</code>
       * @return The imageType.
       */
      @java.lang.Override
      public int getImageType() {
        return imageType_;
      }
      /**
       * <code>int32 image_type = 6;</code>
       * @param value The imageType to set.
       * @return This builder for chaining.
       */
      public Builder setImageType(int value) {
        
        imageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 image_type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageType() {
        
        imageType_ = 0;
        onChanged();
        return this;
      }

      private com.douyin.webcast.ColorInfoSerializer.ColorInfo colorInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.ColorInfoSerializer.ColorInfo, com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder, com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder> colorInfoBuilder_;
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       * @return Whether the colorInfo field is set.
       */
      public boolean hasColorInfo() {
        return colorInfoBuilder_ != null || colorInfo_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       * @return The colorInfo.
       */
      public com.douyin.webcast.ColorInfoSerializer.ColorInfo getColorInfo() {
        if (colorInfoBuilder_ == null) {
          return colorInfo_ == null ? com.douyin.webcast.ColorInfoSerializer.ColorInfo.getDefaultInstance() : colorInfo_;
        } else {
          return colorInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      public Builder setColorInfo(com.douyin.webcast.ColorInfoSerializer.ColorInfo value) {
        if (colorInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          colorInfo_ = value;
          onChanged();
        } else {
          colorInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      public Builder setColorInfo(
          com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder builderForValue) {
        if (colorInfoBuilder_ == null) {
          colorInfo_ = builderForValue.build();
          onChanged();
        } else {
          colorInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      public Builder mergeColorInfo(com.douyin.webcast.ColorInfoSerializer.ColorInfo value) {
        if (colorInfoBuilder_ == null) {
          if (colorInfo_ != null) {
            colorInfo_ =
              com.douyin.webcast.ColorInfoSerializer.ColorInfo.newBuilder(colorInfo_).mergeFrom(value).buildPartial();
          } else {
            colorInfo_ = value;
          }
          onChanged();
        } else {
          colorInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      public Builder clearColorInfo() {
        if (colorInfoBuilder_ == null) {
          colorInfo_ = null;
          onChanged();
        } else {
          colorInfo_ = null;
          colorInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      public com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder getColorInfoBuilder() {
        
        onChanged();
        return getColorInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      public com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder getColorInfoOrBuilder() {
        if (colorInfoBuilder_ != null) {
          return colorInfoBuilder_.getMessageOrBuilder();
        } else {
          return colorInfo_ == null ?
              com.douyin.webcast.ColorInfoSerializer.ColorInfo.getDefaultInstance() : colorInfo_;
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo colorInfo = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.ColorInfoSerializer.ColorInfo, com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder, com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder> 
          getColorInfoFieldBuilder() {
        if (colorInfoBuilder_ == null) {
          colorInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.douyin.webcast.ColorInfoSerializer.ColorInfo, com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder, com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder>(
                  getColorInfo(),
                  getParentForChildren(),
                  isClean());
          colorInfo_ = null;
        }
        return colorInfoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.CoverInfo)
    }

    // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.CoverInfo)
    private static final com.douyin.webcast.CoverInfoSerializer.CoverInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.douyin.webcast.CoverInfoSerializer.CoverInfo();
    }

    public static com.douyin.webcast.CoverInfoSerializer.CoverInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CoverInfo>
        PARSER = new com.google.protobuf.AbstractParser<CoverInfo>() {
      @java.lang.Override
      public CoverInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoverInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CoverInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CoverInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.douyin.webcast.CoverInfoSerializer.CoverInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_CoverInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_CoverInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CoverInfo.proto\022\030com.douyin.webcast.pr" +
      "oto\032\017ColorInfo.proto\"\250\001\n\tCoverInfo\022\020\n\010ur" +
      "l_list\030\001 \003(\t\022\013\n\003uri\030\002 \001(\t\022\016\n\006height\030\003 \001(" +
      "\005\022\r\n\005width\030\004 \001(\005\022\021\n\tavg_color\030\005 \001(\t\022\022\n\ni" +
      "mage_type\030\006 \001(\005\0226\n\tcolorInfo\030\010 \001(\0132#.com" +
      ".douyin.webcast.proto.ColorInfoB)\n\022com.d" +
      "ouyin.webcastB\023CoverInfoSerializerb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.douyin.webcast.ColorInfoSerializer.getDescriptor(),
        });
    internal_static_com_douyin_webcast_proto_CoverInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_douyin_webcast_proto_CoverInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_CoverInfo_descriptor,
        new java.lang.String[] { "UrlList", "Uri", "Height", "Width", "AvgColor", "ImageType", "ColorInfo", });
    com.douyin.webcast.ColorInfoSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
