// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GiftInfo.proto

package com.douyin.webcast;

public final class GiftInfoSerializer {
  private GiftInfoSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GiftInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.GiftInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *  "webcast_aweme_gift_send_message"
     * </pre>
     *
     * <code>string msg_type = 1;</code>
     * @return The msgType.
     */
    java.lang.String getMsgType();
    /**
     * <pre>
     *  "webcast_aweme_gift_send_message"
     * </pre>
     *
     * <code>string msg_type = 1;</code>
     * @return The bytes for msgType.
     */
    com.google.protobuf.ByteString
        getMsgTypeBytes();

    /**
     * <pre>
     *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
     * @return Whether the color field is set.
     */
    boolean hasColor();
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
     * @return The color.
     */
    com.douyin.webcast.ColorInfoSerializer.ColorInfo getColor();
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
     */
    com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder getColorOrBuilder();

    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    java.util.List<com.douyin.webcast.GiftItemSerializer.GiftItem> 
        getGiftsList();
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    com.douyin.webcast.GiftItemSerializer.GiftItem getGifts(int index);
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    int getGiftsCount();
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    java.util.List<? extends com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder> 
        getGiftsOrBuilderList();
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder getGiftsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.douyin.webcast.proto.GiftInfo}
   */
  public static final class GiftInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.GiftInfo)
      GiftInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GiftInfo.newBuilder() to construct.
    private GiftInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GiftInfo() {
      msgType_ = "";
      name_ = "";
      gifts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GiftInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GiftInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder subBuilder = null;
              if (color_ != null) {
                subBuilder = color_.toBuilder();
              }
              color_ = input.readMessage(com.douyin.webcast.ColorInfoSerializer.ColorInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(color_);
                color_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                gifts_ = new java.util.ArrayList<com.douyin.webcast.GiftItemSerializer.GiftItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              gifts_.add(
                  input.readMessage(com.douyin.webcast.GiftItemSerializer.GiftItem.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          gifts_ = java.util.Collections.unmodifiableList(gifts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.douyin.webcast.GiftInfoSerializer.internal_static_com_douyin_webcast_proto_GiftInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.douyin.webcast.GiftInfoSerializer.internal_static_com_douyin_webcast_proto_GiftInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.douyin.webcast.GiftInfoSerializer.GiftInfo.class, com.douyin.webcast.GiftInfoSerializer.GiftInfo.Builder.class);
    }

    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgType_;
    /**
     * <pre>
     *  "webcast_aweme_gift_send_message"
     * </pre>
     *
     * <code>string msg_type = 1;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public java.lang.String getMsgType() {
      java.lang.Object ref = msgType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  "webcast_aweme_gift_send_message"
     * </pre>
     *
     * <code>string msg_type = 1;</code>
     * @return The bytes for msgType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      java.lang.Object ref = msgType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLOR_FIELD_NUMBER = 3;
    private com.douyin.webcast.ColorInfoSerializer.ColorInfo color_;
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
     * @return Whether the color field is set.
     */
    @java.lang.Override
    public boolean hasColor() {
      return color_ != null;
    }
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
     * @return The color.
     */
    @java.lang.Override
    public com.douyin.webcast.ColorInfoSerializer.ColorInfo getColor() {
      return color_ == null ? com.douyin.webcast.ColorInfoSerializer.ColorInfo.getDefaultInstance() : color_;
    }
    /**
     * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder getColorOrBuilder() {
      return getColor();
    }

    public static final int GIFTS_FIELD_NUMBER = 4;
    private java.util.List<com.douyin.webcast.GiftItemSerializer.GiftItem> gifts_;
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    @java.lang.Override
    public java.util.List<com.douyin.webcast.GiftItemSerializer.GiftItem> getGiftsList() {
      return gifts_;
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder> 
        getGiftsOrBuilderList() {
      return gifts_;
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    @java.lang.Override
    public int getGiftsCount() {
      return gifts_.size();
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.GiftItemSerializer.GiftItem getGifts(int index) {
      return gifts_.get(index);
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder getGiftsOrBuilder(
        int index) {
      return gifts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgType_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (color_ != null) {
        output.writeMessage(3, getColor());
      }
      for (int i = 0; i < gifts_.size(); i++) {
        output.writeMessage(4, gifts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgType_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (color_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getColor());
      }
      for (int i = 0; i < gifts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, gifts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.douyin.webcast.GiftInfoSerializer.GiftInfo)) {
        return super.equals(obj);
      }
      com.douyin.webcast.GiftInfoSerializer.GiftInfo other = (com.douyin.webcast.GiftInfoSerializer.GiftInfo) obj;

      if (!getMsgType()
          .equals(other.getMsgType())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (hasColor() != other.hasColor()) return false;
      if (hasColor()) {
        if (!getColor()
            .equals(other.getColor())) return false;
      }
      if (!getGiftsList()
          .equals(other.getGiftsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getColor().hashCode();
      }
      if (getGiftsCount() > 0) {
        hash = (37 * hash) + GIFTS_FIELD_NUMBER;
        hash = (53 * hash) + getGiftsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.douyin.webcast.GiftInfoSerializer.GiftInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.GiftInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.GiftInfo)
        com.douyin.webcast.GiftInfoSerializer.GiftInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.GiftInfoSerializer.internal_static_com_douyin_webcast_proto_GiftInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.GiftInfoSerializer.internal_static_com_douyin_webcast_proto_GiftInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.GiftInfoSerializer.GiftInfo.class, com.douyin.webcast.GiftInfoSerializer.GiftInfo.Builder.class);
      }

      // Construct using com.douyin.webcast.GiftInfoSerializer.GiftInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGiftsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgType_ = "";

        name_ = "";

        if (colorBuilder_ == null) {
          color_ = null;
        } else {
          color_ = null;
          colorBuilder_ = null;
        }
        if (giftsBuilder_ == null) {
          gifts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          giftsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.douyin.webcast.GiftInfoSerializer.internal_static_com_douyin_webcast_proto_GiftInfo_descriptor;
      }

      @java.lang.Override
      public com.douyin.webcast.GiftInfoSerializer.GiftInfo getDefaultInstanceForType() {
        return com.douyin.webcast.GiftInfoSerializer.GiftInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.douyin.webcast.GiftInfoSerializer.GiftInfo build() {
        com.douyin.webcast.GiftInfoSerializer.GiftInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.douyin.webcast.GiftInfoSerializer.GiftInfo buildPartial() {
        com.douyin.webcast.GiftInfoSerializer.GiftInfo result = new com.douyin.webcast.GiftInfoSerializer.GiftInfo(this);
        int from_bitField0_ = bitField0_;
        result.msgType_ = msgType_;
        result.name_ = name_;
        if (colorBuilder_ == null) {
          result.color_ = color_;
        } else {
          result.color_ = colorBuilder_.build();
        }
        if (giftsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            gifts_ = java.util.Collections.unmodifiableList(gifts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.gifts_ = gifts_;
        } else {
          result.gifts_ = giftsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.douyin.webcast.GiftInfoSerializer.GiftInfo) {
          return mergeFrom((com.douyin.webcast.GiftInfoSerializer.GiftInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.douyin.webcast.GiftInfoSerializer.GiftInfo other) {
        if (other == com.douyin.webcast.GiftInfoSerializer.GiftInfo.getDefaultInstance()) return this;
        if (!other.getMsgType().isEmpty()) {
          msgType_ = other.msgType_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasColor()) {
          mergeColor(other.getColor());
        }
        if (giftsBuilder_ == null) {
          if (!other.gifts_.isEmpty()) {
            if (gifts_.isEmpty()) {
              gifts_ = other.gifts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGiftsIsMutable();
              gifts_.addAll(other.gifts_);
            }
            onChanged();
          }
        } else {
          if (!other.gifts_.isEmpty()) {
            if (giftsBuilder_.isEmpty()) {
              giftsBuilder_.dispose();
              giftsBuilder_ = null;
              gifts_ = other.gifts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              giftsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGiftsFieldBuilder() : null;
            } else {
              giftsBuilder_.addAllMessages(other.gifts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.douyin.webcast.GiftInfoSerializer.GiftInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.douyin.webcast.GiftInfoSerializer.GiftInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgType_ = "";
      /**
       * <pre>
       *  "webcast_aweme_gift_send_message"
       * </pre>
       *
       * <code>string msg_type = 1;</code>
       * @return The msgType.
       */
      public java.lang.String getMsgType() {
        java.lang.Object ref = msgType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  "webcast_aweme_gift_send_message"
       * </pre>
       *
       * <code>string msg_type = 1;</code>
       * @return The bytes for msgType.
       */
      public com.google.protobuf.ByteString
          getMsgTypeBytes() {
        java.lang.Object ref = msgType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  "webcast_aweme_gift_send_message"
       * </pre>
       *
       * <code>string msg_type = 1;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  "webcast_aweme_gift_send_message"
       * </pre>
       *
       * <code>string msg_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  "webcast_aweme_gift_send_message"
       * </pre>
       *
       * <code>string msg_type = 1;</code>
       * @param value The bytes for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  "{0:user} &#92;351&#92;200&#92;201&#92;345&#92;207&#92;272{1:gift} {2:string}"
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.douyin.webcast.ColorInfoSerializer.ColorInfo color_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.ColorInfoSerializer.ColorInfo, com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder, com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder> colorBuilder_;
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       * @return Whether the color field is set.
       */
      public boolean hasColor() {
        return colorBuilder_ != null || color_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       * @return The color.
       */
      public com.douyin.webcast.ColorInfoSerializer.ColorInfo getColor() {
        if (colorBuilder_ == null) {
          return color_ == null ? com.douyin.webcast.ColorInfoSerializer.ColorInfo.getDefaultInstance() : color_;
        } else {
          return colorBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      public Builder setColor(com.douyin.webcast.ColorInfoSerializer.ColorInfo value) {
        if (colorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          color_ = value;
          onChanged();
        } else {
          colorBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      public Builder setColor(
          com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder builderForValue) {
        if (colorBuilder_ == null) {
          color_ = builderForValue.build();
          onChanged();
        } else {
          colorBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      public Builder mergeColor(com.douyin.webcast.ColorInfoSerializer.ColorInfo value) {
        if (colorBuilder_ == null) {
          if (color_ != null) {
            color_ =
              com.douyin.webcast.ColorInfoSerializer.ColorInfo.newBuilder(color_).mergeFrom(value).buildPartial();
          } else {
            color_ = value;
          }
          onChanged();
        } else {
          colorBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      public Builder clearColor() {
        if (colorBuilder_ == null) {
          color_ = null;
          onChanged();
        } else {
          color_ = null;
          colorBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      public com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder getColorBuilder() {
        
        onChanged();
        return getColorFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      public com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder getColorOrBuilder() {
        if (colorBuilder_ != null) {
          return colorBuilder_.getMessageOrBuilder();
        } else {
          return color_ == null ?
              com.douyin.webcast.ColorInfoSerializer.ColorInfo.getDefaultInstance() : color_;
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.ColorInfo color = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.ColorInfoSerializer.ColorInfo, com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder, com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder> 
          getColorFieldBuilder() {
        if (colorBuilder_ == null) {
          colorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.douyin.webcast.ColorInfoSerializer.ColorInfo, com.douyin.webcast.ColorInfoSerializer.ColorInfo.Builder, com.douyin.webcast.ColorInfoSerializer.ColorInfoOrBuilder>(
                  getColor(),
                  getParentForChildren(),
                  isClean());
          color_ = null;
        }
        return colorBuilder_;
      }

      private java.util.List<com.douyin.webcast.GiftItemSerializer.GiftItem> gifts_ =
        java.util.Collections.emptyList();
      private void ensureGiftsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          gifts_ = new java.util.ArrayList<com.douyin.webcast.GiftItemSerializer.GiftItem>(gifts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.douyin.webcast.GiftItemSerializer.GiftItem, com.douyin.webcast.GiftItemSerializer.GiftItem.Builder, com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder> giftsBuilder_;

      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public java.util.List<com.douyin.webcast.GiftItemSerializer.GiftItem> getGiftsList() {
        if (giftsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gifts_);
        } else {
          return giftsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public int getGiftsCount() {
        if (giftsBuilder_ == null) {
          return gifts_.size();
        } else {
          return giftsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public com.douyin.webcast.GiftItemSerializer.GiftItem getGifts(int index) {
        if (giftsBuilder_ == null) {
          return gifts_.get(index);
        } else {
          return giftsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder setGifts(
          int index, com.douyin.webcast.GiftItemSerializer.GiftItem value) {
        if (giftsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGiftsIsMutable();
          gifts_.set(index, value);
          onChanged();
        } else {
          giftsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder setGifts(
          int index, com.douyin.webcast.GiftItemSerializer.GiftItem.Builder builderForValue) {
        if (giftsBuilder_ == null) {
          ensureGiftsIsMutable();
          gifts_.set(index, builderForValue.build());
          onChanged();
        } else {
          giftsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder addGifts(com.douyin.webcast.GiftItemSerializer.GiftItem value) {
        if (giftsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGiftsIsMutable();
          gifts_.add(value);
          onChanged();
        } else {
          giftsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder addGifts(
          int index, com.douyin.webcast.GiftItemSerializer.GiftItem value) {
        if (giftsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGiftsIsMutable();
          gifts_.add(index, value);
          onChanged();
        } else {
          giftsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder addGifts(
          com.douyin.webcast.GiftItemSerializer.GiftItem.Builder builderForValue) {
        if (giftsBuilder_ == null) {
          ensureGiftsIsMutable();
          gifts_.add(builderForValue.build());
          onChanged();
        } else {
          giftsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder addGifts(
          int index, com.douyin.webcast.GiftItemSerializer.GiftItem.Builder builderForValue) {
        if (giftsBuilder_ == null) {
          ensureGiftsIsMutable();
          gifts_.add(index, builderForValue.build());
          onChanged();
        } else {
          giftsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder addAllGifts(
          java.lang.Iterable<? extends com.douyin.webcast.GiftItemSerializer.GiftItem> values) {
        if (giftsBuilder_ == null) {
          ensureGiftsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gifts_);
          onChanged();
        } else {
          giftsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder clearGifts() {
        if (giftsBuilder_ == null) {
          gifts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          giftsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public Builder removeGifts(int index) {
        if (giftsBuilder_ == null) {
          ensureGiftsIsMutable();
          gifts_.remove(index);
          onChanged();
        } else {
          giftsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public com.douyin.webcast.GiftItemSerializer.GiftItem.Builder getGiftsBuilder(
          int index) {
        return getGiftsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder getGiftsOrBuilder(
          int index) {
        if (giftsBuilder_ == null) {
          return gifts_.get(index);  } else {
          return giftsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public java.util.List<? extends com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder> 
           getGiftsOrBuilderList() {
        if (giftsBuilder_ != null) {
          return giftsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gifts_);
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public com.douyin.webcast.GiftItemSerializer.GiftItem.Builder addGiftsBuilder() {
        return getGiftsFieldBuilder().addBuilder(
            com.douyin.webcast.GiftItemSerializer.GiftItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public com.douyin.webcast.GiftItemSerializer.GiftItem.Builder addGiftsBuilder(
          int index) {
        return getGiftsFieldBuilder().addBuilder(
            index, com.douyin.webcast.GiftItemSerializer.GiftItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.GiftItem gifts = 4;</code>
       */
      public java.util.List<com.douyin.webcast.GiftItemSerializer.GiftItem.Builder> 
           getGiftsBuilderList() {
        return getGiftsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.douyin.webcast.GiftItemSerializer.GiftItem, com.douyin.webcast.GiftItemSerializer.GiftItem.Builder, com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder> 
          getGiftsFieldBuilder() {
        if (giftsBuilder_ == null) {
          giftsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.douyin.webcast.GiftItemSerializer.GiftItem, com.douyin.webcast.GiftItemSerializer.GiftItem.Builder, com.douyin.webcast.GiftItemSerializer.GiftItemOrBuilder>(
                  gifts_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          gifts_ = null;
        }
        return giftsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.GiftInfo)
    }

    // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.GiftInfo)
    private static final com.douyin.webcast.GiftInfoSerializer.GiftInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.douyin.webcast.GiftInfoSerializer.GiftInfo();
    }

    public static com.douyin.webcast.GiftInfoSerializer.GiftInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GiftInfo>
        PARSER = new com.google.protobuf.AbstractParser<GiftInfo>() {
      @java.lang.Override
      public GiftInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GiftInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GiftInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GiftInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.douyin.webcast.GiftInfoSerializer.GiftInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_GiftInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_GiftInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016GiftInfo.proto\022\030com.douyin.webcast.pro" +
      "to\032\017ColorInfo.proto\032\016GiftItem.proto\"\221\001\n\010" +
      "GiftInfo\022\020\n\010msg_type\030\001 \001(\t\022\014\n\004name\030\002 \001(\t" +
      "\0222\n\005color\030\003 \001(\0132#.com.douyin.webcast.pro" +
      "to.ColorInfo\0221\n\005gifts\030\004 \003(\0132\".com.douyin" +
      ".webcast.proto.GiftItemB(\n\022com.douyin.we" +
      "bcastB\022GiftInfoSerializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.douyin.webcast.ColorInfoSerializer.getDescriptor(),
          com.douyin.webcast.GiftItemSerializer.getDescriptor(),
        });
    internal_static_com_douyin_webcast_proto_GiftInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_douyin_webcast_proto_GiftInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_GiftInfo_descriptor,
        new java.lang.String[] { "MsgType", "Name", "Color", "Gifts", });
    com.douyin.webcast.ColorInfoSerializer.getDescriptor();
    com.douyin.webcast.GiftItemSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
