// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RoomMessage.proto

package com.douyin.webcast;

public final class RoomMessageSerializer {
  private RoomMessageSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.RoomMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    java.util.List<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1> 
        getBodyList();
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 getBody(int index);
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    int getBodyCount();
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    java.util.List<? extends com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder> 
        getBodyOrBuilderList();
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder getBodyOrBuilder(
        int index);

    /**
     * <code>string cursor = 2;</code>
     * @return The cursor.
     */
    java.lang.String getCursor();
    /**
     * <code>string cursor = 2;</code>
     * @return The bytes for cursor.
     */
    com.google.protobuf.ByteString
        getCursorBytes();

    /**
     * <code>int64 time = 3;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>int64 fetch_time = 4;</code>
     * @return The fetchTime.
     */
    long getFetchTime();

    /**
     * <code>string internal_ext = 5;</code>
     * @return The internalExt.
     */
    java.lang.String getInternalExt();
    /**
     * <code>string internal_ext = 5;</code>
     * @return The bytes for internalExt.
     */
    com.google.protobuf.ByteString
        getInternalExtBytes();
  }
  /**
   * Protobuf type {@code com.douyin.webcast.proto.RoomMessage}
   */
  public static final class RoomMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.RoomMessage)
      RoomMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomMessage.newBuilder() to construct.
    private RoomMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomMessage() {
      body_ = java.util.Collections.emptyList();
      cursor_ = "";
      internalExt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RoomMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                body_ = new java.util.ArrayList<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1>();
                mutable_bitField0_ |= 0x00000001;
              }
              body_.add(
                  input.readMessage(com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cursor_ = s;
              break;
            }
            case 24: {

              time_ = input.readInt64();
              break;
            }
            case 32: {

              fetchTime_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              internalExt_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.douyin.webcast.RoomMessageSerializer.RoomMessage.class, com.douyin.webcast.RoomMessageSerializer.RoomMessage.Builder.class);
    }

    public interface RoomMessage_Obj1OrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       **
       *WebcastGiftMessage 送礼物的消息
       * </pre>
       *
       * <code>string messageType = 1;</code>
       * @return The messageType.
       */
      java.lang.String getMessageType();
      /**
       * <pre>
       **
       *WebcastGiftMessage 送礼物的消息
       * </pre>
       *
       * <code>string messageType = 1;</code>
       * @return The bytes for messageType.
       */
      com.google.protobuf.ByteString
          getMessageTypeBytes();

      /**
       * <pre>
       *    message MessageBody{
       *      message TimeInfo{
       *        string messageType = 1;
       *        int64 id1 = 2;
       *        int64 id2 = 3;
       *        int64 now_time = 4;
       *        int32 id3 = 6;
       *        /&#42;*
       *        当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *         *&#47;
       *        string msg = 7;
       *        message GiftSendMessage{
       *          string str1 = 1;
       *          string name = 2;
       *          message SizeInfo{
       *            string color = 1;
       *            int32 bold = 4;
       *          }
       *          SizeInfo size = 3;
       *          message Gift{
       *            int32 id = 1;
       *            SizeInfo size = 2;
       *          }
       *        }
       *        int32 timeInfo_11 = 11;
       *      }
       *      TimeInfo timeInfo = 1;
       *      message UserInfo{
       *        int64 str1 = 1;
       *        //          用户id，短数字类型
       *        int64 id = 2;
       *        string name = 3;
       *        int32 gender = 4;
       *        message CoverInfo{
       *          repeated string url_list = 1;
       *          string uri = 2;
       *          int32 height = 3;
       *          int32 width = 4;
       *          string avg_color = 5;
       *          int32 image_type = 6;
       *          message ColorInfo{
       *            string text = 1;
       *            string color = 2;
       *            int32 type = 3;
       *          }
       *          ColorInfo colorInfo = 8;
       *        }
       *        CoverInfo headimg = 9;
       *        message U_Obj22{
       *          int32 o1 = 1;
       *          int32 o2 = 2;
       *          int32 o3 = 3;
       *        }
       *        U_Obj22 u_obj = 22;
       *        message U_Obj23{
       *          string str19 = 19;
       *          string str20 = 20;
       *        }
       *        U_Obj23 u_obj23 = 23;
       *        string id_str = 38;
       *        //          加密的用户id，访问其它接口时的必备参数
       *        string sec_uid = 46;
       *        int32 authorization_info = 54;
       *      }
       *      UserInfo user_2=2;
       *      string msg_3=3;
       *      MessageBody_Obj_18 messageBody_9=9;
       * //      int32 messageBody_13 = 13;
       * //      message MessageBody_Obj_14{
       * //        string str_1 = 1;
       * //        int32 int_2 = 2;
       * //        int32 int_3 = 3;
       * //      }
       * //      MessageBody_Obj_14 messageBody_14 = 14;
       * //      int32 messageBody_17 = 17;
       *      message MessageBody_Obj_18{
       *        UserInfo.CoverInfo coverinfo_1 = 1;
       *      }
       * //      MessageBody_Obj_18 messageBody_18 = 18;
       * //      string messageBody_19 = 19;
       *    }
       *    MessageBody messageBody = 2;
       * </pre>
       *
       * <code>int64 messageInfo_3 = 3;</code>
       * @return The messageInfo3.
       */
      long getMessageInfo3();
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1}
     */
    public static final class RoomMessage_Obj1 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1)
        RoomMessage_Obj1OrBuilder {
    private static final long serialVersionUID = 0L;
      // Use RoomMessage_Obj1.newBuilder() to construct.
      private RoomMessage_Obj1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private RoomMessage_Obj1() {
        messageType_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new RoomMessage_Obj1();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private RoomMessage_Obj1(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                messageType_ = s;
                break;
              }
              case 24: {

                messageInfo3_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.class, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder.class);
      }

      public static final int MESSAGETYPE_FIELD_NUMBER = 1;
      private volatile java.lang.Object messageType_;
      /**
       * <pre>
       **
       *WebcastGiftMessage 送礼物的消息
       * </pre>
       *
       * <code>string messageType = 1;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       **
       *WebcastGiftMessage 送礼物的消息
       * </pre>
       *
       * <code>string messageType = 1;</code>
       * @return The bytes for messageType.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MESSAGEINFO_3_FIELD_NUMBER = 3;
      private long messageInfo3_;
      /**
       * <pre>
       *    message MessageBody{
       *      message TimeInfo{
       *        string messageType = 1;
       *        int64 id1 = 2;
       *        int64 id2 = 3;
       *        int64 now_time = 4;
       *        int32 id3 = 6;
       *        /&#42;*
       *        当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *         *&#47;
       *        string msg = 7;
       *        message GiftSendMessage{
       *          string str1 = 1;
       *          string name = 2;
       *          message SizeInfo{
       *            string color = 1;
       *            int32 bold = 4;
       *          }
       *          SizeInfo size = 3;
       *          message Gift{
       *            int32 id = 1;
       *            SizeInfo size = 2;
       *          }
       *        }
       *        int32 timeInfo_11 = 11;
       *      }
       *      TimeInfo timeInfo = 1;
       *      message UserInfo{
       *        int64 str1 = 1;
       *        //          用户id，短数字类型
       *        int64 id = 2;
       *        string name = 3;
       *        int32 gender = 4;
       *        message CoverInfo{
       *          repeated string url_list = 1;
       *          string uri = 2;
       *          int32 height = 3;
       *          int32 width = 4;
       *          string avg_color = 5;
       *          int32 image_type = 6;
       *          message ColorInfo{
       *            string text = 1;
       *            string color = 2;
       *            int32 type = 3;
       *          }
       *          ColorInfo colorInfo = 8;
       *        }
       *        CoverInfo headimg = 9;
       *        message U_Obj22{
       *          int32 o1 = 1;
       *          int32 o2 = 2;
       *          int32 o3 = 3;
       *        }
       *        U_Obj22 u_obj = 22;
       *        message U_Obj23{
       *          string str19 = 19;
       *          string str20 = 20;
       *        }
       *        U_Obj23 u_obj23 = 23;
       *        string id_str = 38;
       *        //          加密的用户id，访问其它接口时的必备参数
       *        string sec_uid = 46;
       *        int32 authorization_info = 54;
       *      }
       *      UserInfo user_2=2;
       *      string msg_3=3;
       *      MessageBody_Obj_18 messageBody_9=9;
       * //      int32 messageBody_13 = 13;
       * //      message MessageBody_Obj_14{
       * //        string str_1 = 1;
       * //        int32 int_2 = 2;
       * //        int32 int_3 = 3;
       * //      }
       * //      MessageBody_Obj_14 messageBody_14 = 14;
       * //      int32 messageBody_17 = 17;
       *      message MessageBody_Obj_18{
       *        UserInfo.CoverInfo coverinfo_1 = 1;
       *      }
       * //      MessageBody_Obj_18 messageBody_18 = 18;
       * //      string messageBody_19 = 19;
       *    }
       *    MessageBody messageBody = 2;
       * </pre>
       *
       * <code>int64 messageInfo_3 = 3;</code>
       * @return The messageInfo3.
       */
      @java.lang.Override
      public long getMessageInfo3() {
        return messageInfo3_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getMessageTypeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageType_);
        }
        if (messageInfo3_ != 0L) {
          output.writeInt64(3, messageInfo3_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMessageTypeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageType_);
        }
        if (messageInfo3_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, messageInfo3_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1)) {
          return super.equals(obj);
        }
        com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 other = (com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1) obj;

        if (!getMessageType()
            .equals(other.getMessageType())) return false;
        if (getMessageInfo3()
            != other.getMessageInfo3()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageType().hashCode();
        hash = (37 * hash) + MESSAGEINFO_3_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMessageInfo3());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1)
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.class, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder.class);
        }

        // Construct using com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          messageType_ = "";

          messageInfo3_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_descriptor;
        }

        @java.lang.Override
        public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 getDefaultInstanceForType() {
          return com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.getDefaultInstance();
        }

        @java.lang.Override
        public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 build() {
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 buildPartial() {
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 result = new com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1(this);
          result.messageType_ = messageType_;
          result.messageInfo3_ = messageInfo3_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1) {
            return mergeFrom((com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 other) {
          if (other == com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.getDefaultInstance()) return this;
          if (!other.getMessageType().isEmpty()) {
            messageType_ = other.messageType_;
            onChanged();
          }
          if (other.getMessageInfo3() != 0L) {
            setMessageInfo3(other.getMessageInfo3());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object messageType_ = "";
        /**
         * <pre>
         **
         *WebcastGiftMessage 送礼物的消息
         * </pre>
         *
         * <code>string messageType = 1;</code>
         * @return The messageType.
         */
        public java.lang.String getMessageType() {
          java.lang.Object ref = messageType_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            messageType_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         **
         *WebcastGiftMessage 送礼物的消息
         * </pre>
         *
         * <code>string messageType = 1;</code>
         * @return The bytes for messageType.
         */
        public com.google.protobuf.ByteString
            getMessageTypeBytes() {
          java.lang.Object ref = messageType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            messageType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         **
         *WebcastGiftMessage 送礼物的消息
         * </pre>
         *
         * <code>string messageType = 1;</code>
         * @param value The messageType to set.
         * @return This builder for chaining.
         */
        public Builder setMessageType(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          messageType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         **
         *WebcastGiftMessage 送礼物的消息
         * </pre>
         *
         * <code>string messageType = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearMessageType() {
          
          messageType_ = getDefaultInstance().getMessageType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         **
         *WebcastGiftMessage 送礼物的消息
         * </pre>
         *
         * <code>string messageType = 1;</code>
         * @param value The bytes for messageType to set.
         * @return This builder for chaining.
         */
        public Builder setMessageTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          messageType_ = value;
          onChanged();
          return this;
        }

        private long messageInfo3_ ;
        /**
         * <pre>
         *    message MessageBody{
         *      message TimeInfo{
         *        string messageType = 1;
         *        int64 id1 = 2;
         *        int64 id2 = 3;
         *        int64 now_time = 4;
         *        int32 id3 = 6;
         *        /&#42;*
         *        当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
         *         *&#47;
         *        string msg = 7;
         *        message GiftSendMessage{
         *          string str1 = 1;
         *          string name = 2;
         *          message SizeInfo{
         *            string color = 1;
         *            int32 bold = 4;
         *          }
         *          SizeInfo size = 3;
         *          message Gift{
         *            int32 id = 1;
         *            SizeInfo size = 2;
         *          }
         *        }
         *        int32 timeInfo_11 = 11;
         *      }
         *      TimeInfo timeInfo = 1;
         *      message UserInfo{
         *        int64 str1 = 1;
         *        //          用户id，短数字类型
         *        int64 id = 2;
         *        string name = 3;
         *        int32 gender = 4;
         *        message CoverInfo{
         *          repeated string url_list = 1;
         *          string uri = 2;
         *          int32 height = 3;
         *          int32 width = 4;
         *          string avg_color = 5;
         *          int32 image_type = 6;
         *          message ColorInfo{
         *            string text = 1;
         *            string color = 2;
         *            int32 type = 3;
         *          }
         *          ColorInfo colorInfo = 8;
         *        }
         *        CoverInfo headimg = 9;
         *        message U_Obj22{
         *          int32 o1 = 1;
         *          int32 o2 = 2;
         *          int32 o3 = 3;
         *        }
         *        U_Obj22 u_obj = 22;
         *        message U_Obj23{
         *          string str19 = 19;
         *          string str20 = 20;
         *        }
         *        U_Obj23 u_obj23 = 23;
         *        string id_str = 38;
         *        //          加密的用户id，访问其它接口时的必备参数
         *        string sec_uid = 46;
         *        int32 authorization_info = 54;
         *      }
         *      UserInfo user_2=2;
         *      string msg_3=3;
         *      MessageBody_Obj_18 messageBody_9=9;
         * //      int32 messageBody_13 = 13;
         * //      message MessageBody_Obj_14{
         * //        string str_1 = 1;
         * //        int32 int_2 = 2;
         * //        int32 int_3 = 3;
         * //      }
         * //      MessageBody_Obj_14 messageBody_14 = 14;
         * //      int32 messageBody_17 = 17;
         *      message MessageBody_Obj_18{
         *        UserInfo.CoverInfo coverinfo_1 = 1;
         *      }
         * //      MessageBody_Obj_18 messageBody_18 = 18;
         * //      string messageBody_19 = 19;
         *    }
         *    MessageBody messageBody = 2;
         * </pre>
         *
         * <code>int64 messageInfo_3 = 3;</code>
         * @return The messageInfo3.
         */
        @java.lang.Override
        public long getMessageInfo3() {
          return messageInfo3_;
        }
        /**
         * <pre>
         *    message MessageBody{
         *      message TimeInfo{
         *        string messageType = 1;
         *        int64 id1 = 2;
         *        int64 id2 = 3;
         *        int64 now_time = 4;
         *        int32 id3 = 6;
         *        /&#42;*
         *        当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
         *         *&#47;
         *        string msg = 7;
         *        message GiftSendMessage{
         *          string str1 = 1;
         *          string name = 2;
         *          message SizeInfo{
         *            string color = 1;
         *            int32 bold = 4;
         *          }
         *          SizeInfo size = 3;
         *          message Gift{
         *            int32 id = 1;
         *            SizeInfo size = 2;
         *          }
         *        }
         *        int32 timeInfo_11 = 11;
         *      }
         *      TimeInfo timeInfo = 1;
         *      message UserInfo{
         *        int64 str1 = 1;
         *        //          用户id，短数字类型
         *        int64 id = 2;
         *        string name = 3;
         *        int32 gender = 4;
         *        message CoverInfo{
         *          repeated string url_list = 1;
         *          string uri = 2;
         *          int32 height = 3;
         *          int32 width = 4;
         *          string avg_color = 5;
         *          int32 image_type = 6;
         *          message ColorInfo{
         *            string text = 1;
         *            string color = 2;
         *            int32 type = 3;
         *          }
         *          ColorInfo colorInfo = 8;
         *        }
         *        CoverInfo headimg = 9;
         *        message U_Obj22{
         *          int32 o1 = 1;
         *          int32 o2 = 2;
         *          int32 o3 = 3;
         *        }
         *        U_Obj22 u_obj = 22;
         *        message U_Obj23{
         *          string str19 = 19;
         *          string str20 = 20;
         *        }
         *        U_Obj23 u_obj23 = 23;
         *        string id_str = 38;
         *        //          加密的用户id，访问其它接口时的必备参数
         *        string sec_uid = 46;
         *        int32 authorization_info = 54;
         *      }
         *      UserInfo user_2=2;
         *      string msg_3=3;
         *      MessageBody_Obj_18 messageBody_9=9;
         * //      int32 messageBody_13 = 13;
         * //      message MessageBody_Obj_14{
         * //        string str_1 = 1;
         * //        int32 int_2 = 2;
         * //        int32 int_3 = 3;
         * //      }
         * //      MessageBody_Obj_14 messageBody_14 = 14;
         * //      int32 messageBody_17 = 17;
         *      message MessageBody_Obj_18{
         *        UserInfo.CoverInfo coverinfo_1 = 1;
         *      }
         * //      MessageBody_Obj_18 messageBody_18 = 18;
         * //      string messageBody_19 = 19;
         *    }
         *    MessageBody messageBody = 2;
         * </pre>
         *
         * <code>int64 messageInfo_3 = 3;</code>
         * @param value The messageInfo3 to set.
         * @return This builder for chaining.
         */
        public Builder setMessageInfo3(long value) {
          
          messageInfo3_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *    message MessageBody{
         *      message TimeInfo{
         *        string messageType = 1;
         *        int64 id1 = 2;
         *        int64 id2 = 3;
         *        int64 now_time = 4;
         *        int32 id3 = 6;
         *        /&#42;*
         *        当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
         *         *&#47;
         *        string msg = 7;
         *        message GiftSendMessage{
         *          string str1 = 1;
         *          string name = 2;
         *          message SizeInfo{
         *            string color = 1;
         *            int32 bold = 4;
         *          }
         *          SizeInfo size = 3;
         *          message Gift{
         *            int32 id = 1;
         *            SizeInfo size = 2;
         *          }
         *        }
         *        int32 timeInfo_11 = 11;
         *      }
         *      TimeInfo timeInfo = 1;
         *      message UserInfo{
         *        int64 str1 = 1;
         *        //          用户id，短数字类型
         *        int64 id = 2;
         *        string name = 3;
         *        int32 gender = 4;
         *        message CoverInfo{
         *          repeated string url_list = 1;
         *          string uri = 2;
         *          int32 height = 3;
         *          int32 width = 4;
         *          string avg_color = 5;
         *          int32 image_type = 6;
         *          message ColorInfo{
         *            string text = 1;
         *            string color = 2;
         *            int32 type = 3;
         *          }
         *          ColorInfo colorInfo = 8;
         *        }
         *        CoverInfo headimg = 9;
         *        message U_Obj22{
         *          int32 o1 = 1;
         *          int32 o2 = 2;
         *          int32 o3 = 3;
         *        }
         *        U_Obj22 u_obj = 22;
         *        message U_Obj23{
         *          string str19 = 19;
         *          string str20 = 20;
         *        }
         *        U_Obj23 u_obj23 = 23;
         *        string id_str = 38;
         *        //          加密的用户id，访问其它接口时的必备参数
         *        string sec_uid = 46;
         *        int32 authorization_info = 54;
         *      }
         *      UserInfo user_2=2;
         *      string msg_3=3;
         *      MessageBody_Obj_18 messageBody_9=9;
         * //      int32 messageBody_13 = 13;
         * //      message MessageBody_Obj_14{
         * //        string str_1 = 1;
         * //        int32 int_2 = 2;
         * //        int32 int_3 = 3;
         * //      }
         * //      MessageBody_Obj_14 messageBody_14 = 14;
         * //      int32 messageBody_17 = 17;
         *      message MessageBody_Obj_18{
         *        UserInfo.CoverInfo coverinfo_1 = 1;
         *      }
         * //      MessageBody_Obj_18 messageBody_18 = 18;
         * //      string messageBody_19 = 19;
         *    }
         *    MessageBody messageBody = 2;
         * </pre>
         *
         * <code>int64 messageInfo_3 = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearMessageInfo3() {
          
          messageInfo3_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1)
      }

      // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1)
      private static final com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1();
      }

      public static com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<RoomMessage_Obj1>
          PARSER = new com.google.protobuf.AbstractParser<RoomMessage_Obj1>() {
        @java.lang.Override
        public RoomMessage_Obj1 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RoomMessage_Obj1(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<RoomMessage_Obj1> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<RoomMessage_Obj1> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int BODY_FIELD_NUMBER = 1;
    private java.util.List<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1> body_;
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1> getBodyList() {
      return body_;
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder> 
        getBodyOrBuilderList() {
      return body_;
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    @java.lang.Override
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 getBody(int index) {
      return body_.get(index);
    }
    /**
     * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder getBodyOrBuilder(
        int index) {
      return body_.get(index);
    }

    public static final int CURSOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object cursor_;
    /**
     * <code>string cursor = 2;</code>
     * @return The cursor.
     */
    @java.lang.Override
    public java.lang.String getCursor() {
      java.lang.Object ref = cursor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cursor_ = s;
        return s;
      }
    }
    /**
     * <code>string cursor = 2;</code>
     * @return The bytes for cursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCursorBytes() {
      java.lang.Object ref = cursor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>int64 time = 3;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return time_;
    }

    public static final int FETCH_TIME_FIELD_NUMBER = 4;
    private long fetchTime_;
    /**
     * <code>int64 fetch_time = 4;</code>
     * @return The fetchTime.
     */
    @java.lang.Override
    public long getFetchTime() {
      return fetchTime_;
    }

    public static final int INTERNAL_EXT_FIELD_NUMBER = 5;
    private volatile java.lang.Object internalExt_;
    /**
     * <code>string internal_ext = 5;</code>
     * @return The internalExt.
     */
    @java.lang.Override
    public java.lang.String getInternalExt() {
      java.lang.Object ref = internalExt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        internalExt_ = s;
        return s;
      }
    }
    /**
     * <code>string internal_ext = 5;</code>
     * @return The bytes for internalExt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInternalExtBytes() {
      java.lang.Object ref = internalExt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalExt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < body_.size(); i++) {
        output.writeMessage(1, body_.get(i));
      }
      if (!getCursorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cursor_);
      }
      if (time_ != 0L) {
        output.writeInt64(3, time_);
      }
      if (fetchTime_ != 0L) {
        output.writeInt64(4, fetchTime_);
      }
      if (!getInternalExtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, internalExt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < body_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, body_.get(i));
      }
      if (!getCursorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cursor_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      if (fetchTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, fetchTime_);
      }
      if (!getInternalExtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, internalExt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.douyin.webcast.RoomMessageSerializer.RoomMessage)) {
        return super.equals(obj);
      }
      com.douyin.webcast.RoomMessageSerializer.RoomMessage other = (com.douyin.webcast.RoomMessageSerializer.RoomMessage) obj;

      if (!getBodyList()
          .equals(other.getBodyList())) return false;
      if (!getCursor()
          .equals(other.getCursor())) return false;
      if (getTime()
          != other.getTime()) return false;
      if (getFetchTime()
          != other.getFetchTime()) return false;
      if (!getInternalExt()
          .equals(other.getInternalExt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBodyCount() > 0) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBodyList().hashCode();
      }
      hash = (37 * hash) + CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getCursor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + FETCH_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFetchTime());
      hash = (37 * hash) + INTERNAL_EXT_FIELD_NUMBER;
      hash = (53 * hash) + getInternalExt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.douyin.webcast.RoomMessageSerializer.RoomMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.RoomMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.RoomMessage)
        com.douyin.webcast.RoomMessageSerializer.RoomMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.RoomMessageSerializer.RoomMessage.class, com.douyin.webcast.RoomMessageSerializer.RoomMessage.Builder.class);
      }

      // Construct using com.douyin.webcast.RoomMessageSerializer.RoomMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBodyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bodyBuilder_.clear();
        }
        cursor_ = "";

        time_ = 0L;

        fetchTime_ = 0L;

        internalExt_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.douyin.webcast.RoomMessageSerializer.internal_static_com_douyin_webcast_proto_RoomMessage_descriptor;
      }

      @java.lang.Override
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage getDefaultInstanceForType() {
        return com.douyin.webcast.RoomMessageSerializer.RoomMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage build() {
        com.douyin.webcast.RoomMessageSerializer.RoomMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage buildPartial() {
        com.douyin.webcast.RoomMessageSerializer.RoomMessage result = new com.douyin.webcast.RoomMessageSerializer.RoomMessage(this);
        int from_bitField0_ = bitField0_;
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            body_ = java.util.Collections.unmodifiableList(body_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        result.cursor_ = cursor_;
        result.time_ = time_;
        result.fetchTime_ = fetchTime_;
        result.internalExt_ = internalExt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.douyin.webcast.RoomMessageSerializer.RoomMessage) {
          return mergeFrom((com.douyin.webcast.RoomMessageSerializer.RoomMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.douyin.webcast.RoomMessageSerializer.RoomMessage other) {
        if (other == com.douyin.webcast.RoomMessageSerializer.RoomMessage.getDefaultInstance()) return this;
        if (bodyBuilder_ == null) {
          if (!other.body_.isEmpty()) {
            if (body_.isEmpty()) {
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBodyIsMutable();
              body_.addAll(other.body_);
            }
            onChanged();
          }
        } else {
          if (!other.body_.isEmpty()) {
            if (bodyBuilder_.isEmpty()) {
              bodyBuilder_.dispose();
              bodyBuilder_ = null;
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bodyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBodyFieldBuilder() : null;
            } else {
              bodyBuilder_.addAllMessages(other.body_);
            }
          }
        }
        if (!other.getCursor().isEmpty()) {
          cursor_ = other.cursor_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getFetchTime() != 0L) {
          setFetchTime(other.getFetchTime());
        }
        if (!other.getInternalExt().isEmpty()) {
          internalExt_ = other.internalExt_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.douyin.webcast.RoomMessageSerializer.RoomMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.douyin.webcast.RoomMessageSerializer.RoomMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1> body_ =
        java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          body_ = new java.util.ArrayList<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1>(body_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder> bodyBuilder_;

      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public java.util.List<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1> getBodyList() {
        if (bodyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(body_);
        } else {
          return bodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public int getBodyCount() {
        if (bodyBuilder_ == null) {
          return body_.size();
        } else {
          return bodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 getBody(int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);
        } else {
          return bodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder setBody(
          int index, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.set(index, value);
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder setBody(
          int index, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.set(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder addBody(com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder addBody(
          int index, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1 value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(index, value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder addBody(
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder addBody(
          int index, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder addAllBody(
          java.lang.Iterable<? extends com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1> values) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, body_);
          onChanged();
        } else {
          bodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public Builder removeBody(int index) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.remove(index);
          onChanged();
        } else {
          bodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder getBodyBuilder(
          int index) {
        return getBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder getBodyOrBuilder(
          int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);  } else {
          return bodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public java.util.List<? extends com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder> 
           getBodyOrBuilderList() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(body_);
        }
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder addBodyBuilder() {
        return getBodyFieldBuilder().addBuilder(
            com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.getDefaultInstance());
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder addBodyBuilder(
          int index) {
        return getBodyFieldBuilder().addBuilder(
            index, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.getDefaultInstance());
      }
      /**
       * <code>repeated .com.douyin.webcast.proto.RoomMessage.RoomMessage_Obj1 body = 1;</code>
       */
      public java.util.List<com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder> 
           getBodyBuilderList() {
        return getBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1.Builder, com.douyin.webcast.RoomMessageSerializer.RoomMessage.RoomMessage_Obj1OrBuilder>(
                  body_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }

      private java.lang.Object cursor_ = "";
      /**
       * <code>string cursor = 2;</code>
       * @return The cursor.
       */
      public java.lang.String getCursor() {
        java.lang.Object ref = cursor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cursor_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cursor = 2;</code>
       * @return The bytes for cursor.
       */
      public com.google.protobuf.ByteString
          getCursorBytes() {
        java.lang.Object ref = cursor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cursor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cursor = 2;</code>
       * @param value The cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cursor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cursor = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCursor() {
        
        cursor_ = getDefaultInstance().getCursor();
        onChanged();
        return this;
      }
      /**
       * <code>string cursor = 2;</code>
       * @param value The bytes for cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cursor_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 3;</code>
       * @return The time.
       */
      @java.lang.Override
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 3;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private long fetchTime_ ;
      /**
       * <code>int64 fetch_time = 4;</code>
       * @return The fetchTime.
       */
      @java.lang.Override
      public long getFetchTime() {
        return fetchTime_;
      }
      /**
       * <code>int64 fetch_time = 4;</code>
       * @param value The fetchTime to set.
       * @return This builder for chaining.
       */
      public Builder setFetchTime(long value) {
        
        fetchTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fetch_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchTime() {
        
        fetchTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object internalExt_ = "";
      /**
       * <code>string internal_ext = 5;</code>
       * @return The internalExt.
       */
      public java.lang.String getInternalExt() {
        java.lang.Object ref = internalExt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          internalExt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string internal_ext = 5;</code>
       * @return The bytes for internalExt.
       */
      public com.google.protobuf.ByteString
          getInternalExtBytes() {
        java.lang.Object ref = internalExt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          internalExt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string internal_ext = 5;</code>
       * @param value The internalExt to set.
       * @return This builder for chaining.
       */
      public Builder setInternalExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        internalExt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string internal_ext = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInternalExt() {
        
        internalExt_ = getDefaultInstance().getInternalExt();
        onChanged();
        return this;
      }
      /**
       * <code>string internal_ext = 5;</code>
       * @param value The bytes for internalExt to set.
       * @return This builder for chaining.
       */
      public Builder setInternalExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        internalExt_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.RoomMessage)
    }

    // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.RoomMessage)
    private static final com.douyin.webcast.RoomMessageSerializer.RoomMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.douyin.webcast.RoomMessageSerializer.RoomMessage();
    }

    public static com.douyin.webcast.RoomMessageSerializer.RoomMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomMessage>
        PARSER = new com.google.protobuf.AbstractParser<RoomMessage>() {
      @java.lang.Override
      public RoomMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.douyin.webcast.RoomMessageSerializer.RoomMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_RoomMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_RoomMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021RoomMessage.proto\022\030com.douyin.webcast." +
      "proto\"\333\001\n\013RoomMessage\022D\n\004body\030\001 \003(\01326.co" +
      "m.douyin.webcast.proto.RoomMessage.RoomM" +
      "essage_Obj1\022\016\n\006cursor\030\002 \001(\t\022\014\n\004time\030\003 \001(" +
      "\003\022\022\n\nfetch_time\030\004 \001(\003\022\024\n\014internal_ext\030\005 " +
      "\001(\t\032>\n\020RoomMessage_Obj1\022\023\n\013messageType\030\001" +
      " \001(\t\022\025\n\rmessageInfo_3\030\003 \001(\003B+\n\022com.douyi" +
      "n.webcastB\025RoomMessageSerializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_douyin_webcast_proto_RoomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_douyin_webcast_proto_RoomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_RoomMessage_descriptor,
        new java.lang.String[] { "Body", "Cursor", "Time", "FetchTime", "InternalExt", });
    internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_descriptor =
      internal_static_com_douyin_webcast_proto_RoomMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_RoomMessage_RoomMessage_Obj1_descriptor,
        new java.lang.String[] { "MessageType", "MessageInfo3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
