// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimeInfo.proto

package com.douyin.webcast;

public final class TimeInfoSerializer {
  private TimeInfoSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.TimeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string messageType = 1;</code>
     * @return The messageType.
     */
    java.lang.String getMessageType();
    /**
     * <code>string messageType = 1;</code>
     * @return The bytes for messageType.
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <code>int64 id1 = 2;</code>
     * @return The id1.
     */
    long getId1();

    /**
     * <code>int64 id2 = 3;</code>
     * @return The id2.
     */
    long getId2();

    /**
     * <code>int64 now_time = 4;</code>
     * @return The nowTime.
     */
    long getNowTime();

    /**
     * <code>int32 id3 = 6;</code>
     * @return The id3.
     */
    int getId3();

    /**
     * <pre>
     *  /&#42;*
     *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
     *   *&#47;
     * </pre>
     *
     * <code>string msg = 7;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <pre>
     *  /&#42;*
     *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
     *   *&#47;
     * </pre>
     *
     * <code>string msg = 7;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>int32 timeInfo_11 = 11;</code>
     * @return The timeInfo11.
     */
    int getTimeInfo11();
  }
  /**
   * Protobuf type {@code com.douyin.webcast.proto.TimeInfo}
   */
  public static final class TimeInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.TimeInfo)
      TimeInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TimeInfo.newBuilder() to construct.
    private TimeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeInfo() {
      messageType_ = "";
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TimeInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              messageType_ = s;
              break;
            }
            case 16: {

              id1_ = input.readInt64();
              break;
            }
            case 24: {

              id2_ = input.readInt64();
              break;
            }
            case 32: {

              nowTime_ = input.readInt64();
              break;
            }
            case 48: {

              id3_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 88: {

              timeInfo11_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.douyin.webcast.TimeInfoSerializer.internal_static_com_douyin_webcast_proto_TimeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.douyin.webcast.TimeInfoSerializer.internal_static_com_douyin_webcast_proto_TimeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.douyin.webcast.TimeInfoSerializer.TimeInfo.class, com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder.class);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object messageType_;
    /**
     * <code>string messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      }
    }
    /**
     * <code>string messageType = 1;</code>
     * @return The bytes for messageType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID1_FIELD_NUMBER = 2;
    private long id1_;
    /**
     * <code>int64 id1 = 2;</code>
     * @return The id1.
     */
    @java.lang.Override
    public long getId1() {
      return id1_;
    }

    public static final int ID2_FIELD_NUMBER = 3;
    private long id2_;
    /**
     * <code>int64 id2 = 3;</code>
     * @return The id2.
     */
    @java.lang.Override
    public long getId2() {
      return id2_;
    }

    public static final int NOW_TIME_FIELD_NUMBER = 4;
    private long nowTime_;
    /**
     * <code>int64 now_time = 4;</code>
     * @return The nowTime.
     */
    @java.lang.Override
    public long getNowTime() {
      return nowTime_;
    }

    public static final int ID3_FIELD_NUMBER = 6;
    private int id3_;
    /**
     * <code>int32 id3 = 6;</code>
     * @return The id3.
     */
    @java.lang.Override
    public int getId3() {
      return id3_;
    }

    public static final int MSG_FIELD_NUMBER = 7;
    private volatile java.lang.Object msg_;
    /**
     * <pre>
     *  /&#42;*
     *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
     *   *&#47;
     * </pre>
     *
     * <code>string msg = 7;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *  /&#42;*
     *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
     *   *&#47;
     * </pre>
     *
     * <code>string msg = 7;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMEINFO_11_FIELD_NUMBER = 11;
    private int timeInfo11_;
    /**
     * <code>int32 timeInfo_11 = 11;</code>
     * @return The timeInfo11.
     */
    @java.lang.Override
    public int getTimeInfo11() {
      return timeInfo11_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageType_);
      }
      if (id1_ != 0L) {
        output.writeInt64(2, id1_);
      }
      if (id2_ != 0L) {
        output.writeInt64(3, id2_);
      }
      if (nowTime_ != 0L) {
        output.writeInt64(4, nowTime_);
      }
      if (id3_ != 0) {
        output.writeInt32(6, id3_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msg_);
      }
      if (timeInfo11_ != 0) {
        output.writeInt32(11, timeInfo11_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageType_);
      }
      if (id1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id1_);
      }
      if (id2_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, id2_);
      }
      if (nowTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, nowTime_);
      }
      if (id3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, id3_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msg_);
      }
      if (timeInfo11_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, timeInfo11_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.douyin.webcast.TimeInfoSerializer.TimeInfo)) {
        return super.equals(obj);
      }
      com.douyin.webcast.TimeInfoSerializer.TimeInfo other = (com.douyin.webcast.TimeInfoSerializer.TimeInfo) obj;

      if (!getMessageType()
          .equals(other.getMessageType())) return false;
      if (getId1()
          != other.getId1()) return false;
      if (getId2()
          != other.getId2()) return false;
      if (getNowTime()
          != other.getNowTime()) return false;
      if (getId3()
          != other.getId3()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (getTimeInfo11()
          != other.getTimeInfo11()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
      hash = (37 * hash) + ID1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId1());
      hash = (37 * hash) + ID2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId2());
      hash = (37 * hash) + NOW_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNowTime());
      hash = (37 * hash) + ID3_FIELD_NUMBER;
      hash = (53 * hash) + getId3();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (37 * hash) + TIMEINFO_11_FIELD_NUMBER;
      hash = (53 * hash) + getTimeInfo11();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.douyin.webcast.TimeInfoSerializer.TimeInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.TimeInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.TimeInfo)
        com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.TimeInfoSerializer.internal_static_com_douyin_webcast_proto_TimeInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.TimeInfoSerializer.internal_static_com_douyin_webcast_proto_TimeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.TimeInfoSerializer.TimeInfo.class, com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder.class);
      }

      // Construct using com.douyin.webcast.TimeInfoSerializer.TimeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = "";

        id1_ = 0L;

        id2_ = 0L;

        nowTime_ = 0L;

        id3_ = 0;

        msg_ = "";

        timeInfo11_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.douyin.webcast.TimeInfoSerializer.internal_static_com_douyin_webcast_proto_TimeInfo_descriptor;
      }

      @java.lang.Override
      public com.douyin.webcast.TimeInfoSerializer.TimeInfo getDefaultInstanceForType() {
        return com.douyin.webcast.TimeInfoSerializer.TimeInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.douyin.webcast.TimeInfoSerializer.TimeInfo build() {
        com.douyin.webcast.TimeInfoSerializer.TimeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.douyin.webcast.TimeInfoSerializer.TimeInfo buildPartial() {
        com.douyin.webcast.TimeInfoSerializer.TimeInfo result = new com.douyin.webcast.TimeInfoSerializer.TimeInfo(this);
        result.messageType_ = messageType_;
        result.id1_ = id1_;
        result.id2_ = id2_;
        result.nowTime_ = nowTime_;
        result.id3_ = id3_;
        result.msg_ = msg_;
        result.timeInfo11_ = timeInfo11_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.douyin.webcast.TimeInfoSerializer.TimeInfo) {
          return mergeFrom((com.douyin.webcast.TimeInfoSerializer.TimeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.douyin.webcast.TimeInfoSerializer.TimeInfo other) {
        if (other == com.douyin.webcast.TimeInfoSerializer.TimeInfo.getDefaultInstance()) return this;
        if (!other.getMessageType().isEmpty()) {
          messageType_ = other.messageType_;
          onChanged();
        }
        if (other.getId1() != 0L) {
          setId1(other.getId1());
        }
        if (other.getId2() != 0L) {
          setId2(other.getId2());
        }
        if (other.getNowTime() != 0L) {
          setNowTime(other.getNowTime());
        }
        if (other.getId3() != 0) {
          setId3(other.getId3());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.getTimeInfo11() != 0) {
          setTimeInfo11(other.getTimeInfo11());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.douyin.webcast.TimeInfoSerializer.TimeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.douyin.webcast.TimeInfoSerializer.TimeInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object messageType_ = "";
      /**
       * <code>string messageType = 1;</code>
       * @return The messageType.
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageType = 1;</code>
       * @return The bytes for messageType.
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageType = 1;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        
        messageType_ = getDefaultInstance().getMessageType();
        onChanged();
        return this;
      }
      /**
       * <code>string messageType = 1;</code>
       * @param value The bytes for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageType_ = value;
        onChanged();
        return this;
      }

      private long id1_ ;
      /**
       * <code>int64 id1 = 2;</code>
       * @return The id1.
       */
      @java.lang.Override
      public long getId1() {
        return id1_;
      }
      /**
       * <code>int64 id1 = 2;</code>
       * @param value The id1 to set.
       * @return This builder for chaining.
       */
      public Builder setId1(long value) {
        
        id1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId1() {
        
        id1_ = 0L;
        onChanged();
        return this;
      }

      private long id2_ ;
      /**
       * <code>int64 id2 = 3;</code>
       * @return The id2.
       */
      @java.lang.Override
      public long getId2() {
        return id2_;
      }
      /**
       * <code>int64 id2 = 3;</code>
       * @param value The id2 to set.
       * @return This builder for chaining.
       */
      public Builder setId2(long value) {
        
        id2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id2 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearId2() {
        
        id2_ = 0L;
        onChanged();
        return this;
      }

      private long nowTime_ ;
      /**
       * <code>int64 now_time = 4;</code>
       * @return The nowTime.
       */
      @java.lang.Override
      public long getNowTime() {
        return nowTime_;
      }
      /**
       * <code>int64 now_time = 4;</code>
       * @param value The nowTime to set.
       * @return This builder for chaining.
       */
      public Builder setNowTime(long value) {
        
        nowTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 now_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNowTime() {
        
        nowTime_ = 0L;
        onChanged();
        return this;
      }

      private int id3_ ;
      /**
       * <code>int32 id3 = 6;</code>
       * @return The id3.
       */
      @java.lang.Override
      public int getId3() {
        return id3_;
      }
      /**
       * <code>int32 id3 = 6;</code>
       * @param value The id3 to set.
       * @return This builder for chaining.
       */
      public Builder setId3(int value) {
        
        id3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id3 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearId3() {
        
        id3_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <pre>
       *  /&#42;*
       *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *   *&#47;
       * </pre>
       *
       * <code>string msg = 7;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *  /&#42;*
       *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *   *&#47;
       * </pre>
       *
       * <code>string msg = 7;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *  /&#42;*
       *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *   *&#47;
       * </pre>
       *
       * <code>string msg = 7;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  /&#42;*
       *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *   *&#47;
       * </pre>
       *
       * <code>string msg = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *  /&#42;*
       *  当messageTpye=WebcastGiftMessage时，这里显示类似“用户6788522880187:送给主播 1个小心心”的送礼物消息
       *   *&#47;
       * </pre>
       *
       * <code>string msg = 7;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private int timeInfo11_ ;
      /**
       * <code>int32 timeInfo_11 = 11;</code>
       * @return The timeInfo11.
       */
      @java.lang.Override
      public int getTimeInfo11() {
        return timeInfo11_;
      }
      /**
       * <code>int32 timeInfo_11 = 11;</code>
       * @param value The timeInfo11 to set.
       * @return This builder for chaining.
       */
      public Builder setTimeInfo11(int value) {
        
        timeInfo11_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 timeInfo_11 = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeInfo11() {
        
        timeInfo11_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.TimeInfo)
    }

    // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.TimeInfo)
    private static final com.douyin.webcast.TimeInfoSerializer.TimeInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.douyin.webcast.TimeInfoSerializer.TimeInfo();
    }

    public static com.douyin.webcast.TimeInfoSerializer.TimeInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeInfo>
        PARSER = new com.google.protobuf.AbstractParser<TimeInfo>() {
      @java.lang.Override
      public TimeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TimeInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.douyin.webcast.TimeInfoSerializer.TimeInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_TimeInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_TimeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016TimeInfo.proto\022\030com.douyin.webcast.pro" +
      "to\"z\n\010TimeInfo\022\023\n\013messageType\030\001 \001(\t\022\013\n\003i" +
      "d1\030\002 \001(\003\022\013\n\003id2\030\003 \001(\003\022\020\n\010now_time\030\004 \001(\003\022" +
      "\013\n\003id3\030\006 \001(\005\022\013\n\003msg\030\007 \001(\t\022\023\n\013timeInfo_11" +
      "\030\013 \001(\005B(\n\022com.douyin.webcastB\022TimeInfoSe" +
      "rializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_douyin_webcast_proto_TimeInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_douyin_webcast_proto_TimeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_TimeInfo_descriptor,
        new java.lang.String[] { "MessageType", "Id1", "Id2", "NowTime", "Id3", "Msg", "TimeInfo11", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
