// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInfo.proto

package com.douyin.webcast;

public final class UserInfoSerializer {
  private UserInfoSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 str1 = 1;</code>
     * @return The str1.
     */
    long getStr1();

    /**
     * <pre>
     *          用户id，短数字类型
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 gender = 4;</code>
     * @return The gender.
     */
    int getGender();

    /**
     * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
     * @return Whether the headimg field is set.
     */
    boolean hasHeadimg();
    /**
     * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
     * @return The headimg.
     */
    com.douyin.webcast.CoverInfoSerializer.CoverInfo getHeadimg();
    /**
     * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
     */
    com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder getHeadimgOrBuilder();

    /**
     * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
     * @return Whether the uObj field is set.
     */
    boolean hasUObj();
    /**
     * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
     * @return The uObj.
     */
    com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 getUObj();
    /**
     * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
     */
    com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder getUObjOrBuilder();

    /**
     * <code>string id_str = 38;</code>
     * @return The idStr.
     */
    java.lang.String getIdStr();
    /**
     * <code>string id_str = 38;</code>
     * @return The bytes for idStr.
     */
    com.google.protobuf.ByteString
        getIdStrBytes();

    /**
     * <pre>
     *          加密的用户id，访问其它接口时的必备参数
     * </pre>
     *
     * <code>string sec_uid = 46;</code>
     * @return The secUid.
     */
    java.lang.String getSecUid();
    /**
     * <pre>
     *          加密的用户id，访问其它接口时的必备参数
     * </pre>
     *
     * <code>string sec_uid = 46;</code>
     * @return The bytes for secUid.
     */
    com.google.protobuf.ByteString
        getSecUidBytes();

    /**
     * <code>int32 authorization_info = 54;</code>
     * @return The authorizationInfo.
     */
    int getAuthorizationInfo();
  }
  /**
   * Protobuf type {@code com.douyin.webcast.proto.UserInfo}
   */
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      name_ = "";
      idStr_ = "";
      secUid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              str1_ = input.readInt64();
              break;
            }
            case 16: {

              id_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              gender_ = input.readInt32();
              break;
            }
            case 74: {
              com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder subBuilder = null;
              if (headimg_ != null) {
                subBuilder = headimg_.toBuilder();
              }
              headimg_ = input.readMessage(com.douyin.webcast.CoverInfoSerializer.CoverInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(headimg_);
                headimg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 178: {
              com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder subBuilder = null;
              if (uObj_ != null) {
                subBuilder = uObj_.toBuilder();
              }
              uObj_ = input.readMessage(com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(uObj_);
                uObj_ = subBuilder.buildPartial();
              }

              break;
            }
            case 306: {
              java.lang.String s = input.readStringRequireUtf8();

              idStr_ = s;
              break;
            }
            case 370: {
              java.lang.String s = input.readStringRequireUtf8();

              secUid_ = s;
              break;
            }
            case 432: {

              authorizationInfo_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.douyin.webcast.UserInfoSerializer.UserInfo.class, com.douyin.webcast.UserInfoSerializer.UserInfo.Builder.class);
    }

    public interface U_Obj22OrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.UserInfo.U_Obj22)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 o1 = 1;</code>
       * @return The o1.
       */
      int getO1();

      /**
       * <code>int32 o2 = 2;</code>
       * @return The o2.
       */
      int getO2();

      /**
       * <code>int32 o3 = 3;</code>
       * @return The o3.
       */
      int getO3();
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.UserInfo.U_Obj22}
     */
    public static final class U_Obj22 extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.UserInfo.U_Obj22)
        U_Obj22OrBuilder {
    private static final long serialVersionUID = 0L;
      // Use U_Obj22.newBuilder() to construct.
      private U_Obj22(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private U_Obj22() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new U_Obj22();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private U_Obj22(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                o1_ = input.readInt32();
                break;
              }
              case 16: {

                o2_ = input.readInt32();
                break;
              }
              case 24: {

                o3_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.class, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder.class);
      }

      public static final int O1_FIELD_NUMBER = 1;
      private int o1_;
      /**
       * <code>int32 o1 = 1;</code>
       * @return The o1.
       */
      @java.lang.Override
      public int getO1() {
        return o1_;
      }

      public static final int O2_FIELD_NUMBER = 2;
      private int o2_;
      /**
       * <code>int32 o2 = 2;</code>
       * @return The o2.
       */
      @java.lang.Override
      public int getO2() {
        return o2_;
      }

      public static final int O3_FIELD_NUMBER = 3;
      private int o3_;
      /**
       * <code>int32 o3 = 3;</code>
       * @return The o3.
       */
      @java.lang.Override
      public int getO3() {
        return o3_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (o1_ != 0) {
          output.writeInt32(1, o1_);
        }
        if (o2_ != 0) {
          output.writeInt32(2, o2_);
        }
        if (o3_ != 0) {
          output.writeInt32(3, o3_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (o1_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, o1_);
        }
        if (o2_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, o2_);
        }
        if (o3_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, o3_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22)) {
          return super.equals(obj);
        }
        com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 other = (com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22) obj;

        if (getO1()
            != other.getO1()) return false;
        if (getO2()
            != other.getO2()) return false;
        if (getO3()
            != other.getO3()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + O1_FIELD_NUMBER;
        hash = (53 * hash) + getO1();
        hash = (37 * hash) + O2_FIELD_NUMBER;
        hash = (53 * hash) + getO2();
        hash = (37 * hash) + O3_FIELD_NUMBER;
        hash = (53 * hash) + getO3();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.douyin.webcast.proto.UserInfo.U_Obj22}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.UserInfo.U_Obj22)
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.class, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder.class);
        }

        // Construct using com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          o1_ = 0;

          o2_ = 0;

          o3_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_descriptor;
        }

        @java.lang.Override
        public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 getDefaultInstanceForType() {
          return com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.getDefaultInstance();
        }

        @java.lang.Override
        public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 build() {
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 buildPartial() {
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 result = new com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22(this);
          result.o1_ = o1_;
          result.o2_ = o2_;
          result.o3_ = o3_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22) {
            return mergeFrom((com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 other) {
          if (other == com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.getDefaultInstance()) return this;
          if (other.getO1() != 0) {
            setO1(other.getO1());
          }
          if (other.getO2() != 0) {
            setO2(other.getO2());
          }
          if (other.getO3() != 0) {
            setO3(other.getO3());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int o1_ ;
        /**
         * <code>int32 o1 = 1;</code>
         * @return The o1.
         */
        @java.lang.Override
        public int getO1() {
          return o1_;
        }
        /**
         * <code>int32 o1 = 1;</code>
         * @param value The o1 to set.
         * @return This builder for chaining.
         */
        public Builder setO1(int value) {
          
          o1_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 o1 = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearO1() {
          
          o1_ = 0;
          onChanged();
          return this;
        }

        private int o2_ ;
        /**
         * <code>int32 o2 = 2;</code>
         * @return The o2.
         */
        @java.lang.Override
        public int getO2() {
          return o2_;
        }
        /**
         * <code>int32 o2 = 2;</code>
         * @param value The o2 to set.
         * @return This builder for chaining.
         */
        public Builder setO2(int value) {
          
          o2_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 o2 = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearO2() {
          
          o2_ = 0;
          onChanged();
          return this;
        }

        private int o3_ ;
        /**
         * <code>int32 o3 = 3;</code>
         * @return The o3.
         */
        @java.lang.Override
        public int getO3() {
          return o3_;
        }
        /**
         * <code>int32 o3 = 3;</code>
         * @param value The o3 to set.
         * @return This builder for chaining.
         */
        public Builder setO3(int value) {
          
          o3_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 o3 = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearO3() {
          
          o3_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.UserInfo.U_Obj22)
      }

      // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.UserInfo.U_Obj22)
      private static final com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22();
      }

      public static com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<U_Obj22>
          PARSER = new com.google.protobuf.AbstractParser<U_Obj22>() {
        @java.lang.Override
        public U_Obj22 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new U_Obj22(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<U_Obj22> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<U_Obj22> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STR1_FIELD_NUMBER = 1;
    private long str1_;
    /**
     * <code>int64 str1 = 1;</code>
     * @return The str1.
     */
    @java.lang.Override
    public long getStr1() {
      return str1_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *          用户id，短数字类型
     * </pre>
     *
     * <code>int64 id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 4;
    private int gender_;
    /**
     * <code>int32 gender = 4;</code>
     * @return The gender.
     */
    @java.lang.Override
    public int getGender() {
      return gender_;
    }

    public static final int HEADIMG_FIELD_NUMBER = 9;
    private com.douyin.webcast.CoverInfoSerializer.CoverInfo headimg_;
    /**
     * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
     * @return Whether the headimg field is set.
     */
    @java.lang.Override
    public boolean hasHeadimg() {
      return headimg_ != null;
    }
    /**
     * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
     * @return The headimg.
     */
    @java.lang.Override
    public com.douyin.webcast.CoverInfoSerializer.CoverInfo getHeadimg() {
      return headimg_ == null ? com.douyin.webcast.CoverInfoSerializer.CoverInfo.getDefaultInstance() : headimg_;
    }
    /**
     * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder getHeadimgOrBuilder() {
      return getHeadimg();
    }

    public static final int U_OBJ_FIELD_NUMBER = 22;
    private com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 uObj_;
    /**
     * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
     * @return Whether the uObj field is set.
     */
    @java.lang.Override
    public boolean hasUObj() {
      return uObj_ != null;
    }
    /**
     * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
     * @return The uObj.
     */
    @java.lang.Override
    public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 getUObj() {
      return uObj_ == null ? com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.getDefaultInstance() : uObj_;
    }
    /**
     * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder getUObjOrBuilder() {
      return getUObj();
    }

    public static final int ID_STR_FIELD_NUMBER = 38;
    private volatile java.lang.Object idStr_;
    /**
     * <code>string id_str = 38;</code>
     * @return The idStr.
     */
    @java.lang.Override
    public java.lang.String getIdStr() {
      java.lang.Object ref = idStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idStr_ = s;
        return s;
      }
    }
    /**
     * <code>string id_str = 38;</code>
     * @return The bytes for idStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdStrBytes() {
      java.lang.Object ref = idStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEC_UID_FIELD_NUMBER = 46;
    private volatile java.lang.Object secUid_;
    /**
     * <pre>
     *          加密的用户id，访问其它接口时的必备参数
     * </pre>
     *
     * <code>string sec_uid = 46;</code>
     * @return The secUid.
     */
    @java.lang.Override
    public java.lang.String getSecUid() {
      java.lang.Object ref = secUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *          加密的用户id，访问其它接口时的必备参数
     * </pre>
     *
     * <code>string sec_uid = 46;</code>
     * @return The bytes for secUid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecUidBytes() {
      java.lang.Object ref = secUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHORIZATION_INFO_FIELD_NUMBER = 54;
    private int authorizationInfo_;
    /**
     * <code>int32 authorization_info = 54;</code>
     * @return The authorizationInfo.
     */
    @java.lang.Override
    public int getAuthorizationInfo() {
      return authorizationInfo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (str1_ != 0L) {
        output.writeInt64(1, str1_);
      }
      if (id_ != 0L) {
        output.writeInt64(2, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (gender_ != 0) {
        output.writeInt32(4, gender_);
      }
      if (headimg_ != null) {
        output.writeMessage(9, getHeadimg());
      }
      if (uObj_ != null) {
        output.writeMessage(22, getUObj());
      }
      if (!getIdStrBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 38, idStr_);
      }
      if (!getSecUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 46, secUid_);
      }
      if (authorizationInfo_ != 0) {
        output.writeInt32(54, authorizationInfo_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (str1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, str1_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (gender_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, gender_);
      }
      if (headimg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getHeadimg());
      }
      if (uObj_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(22, getUObj());
      }
      if (!getIdStrBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(38, idStr_);
      }
      if (!getSecUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(46, secUid_);
      }
      if (authorizationInfo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(54, authorizationInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.douyin.webcast.UserInfoSerializer.UserInfo)) {
        return super.equals(obj);
      }
      com.douyin.webcast.UserInfoSerializer.UserInfo other = (com.douyin.webcast.UserInfoSerializer.UserInfo) obj;

      if (getStr1()
          != other.getStr1()) return false;
      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getGender()
          != other.getGender()) return false;
      if (hasHeadimg() != other.hasHeadimg()) return false;
      if (hasHeadimg()) {
        if (!getHeadimg()
            .equals(other.getHeadimg())) return false;
      }
      if (hasUObj() != other.hasUObj()) return false;
      if (hasUObj()) {
        if (!getUObj()
            .equals(other.getUObj())) return false;
      }
      if (!getIdStr()
          .equals(other.getIdStr())) return false;
      if (!getSecUid()
          .equals(other.getSecUid())) return false;
      if (getAuthorizationInfo()
          != other.getAuthorizationInfo()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STR1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStr1());
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + getGender();
      if (hasHeadimg()) {
        hash = (37 * hash) + HEADIMG_FIELD_NUMBER;
        hash = (53 * hash) + getHeadimg().hashCode();
      }
      if (hasUObj()) {
        hash = (37 * hash) + U_OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getUObj().hashCode();
      }
      hash = (37 * hash) + ID_STR_FIELD_NUMBER;
      hash = (53 * hash) + getIdStr().hashCode();
      hash = (37 * hash) + SEC_UID_FIELD_NUMBER;
      hash = (53 * hash) + getSecUid().hashCode();
      hash = (37 * hash) + AUTHORIZATION_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorizationInfo();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.UserInfoSerializer.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.douyin.webcast.UserInfoSerializer.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.UserInfo)
        com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.UserInfoSerializer.UserInfo.class, com.douyin.webcast.UserInfoSerializer.UserInfo.Builder.class);
      }

      // Construct using com.douyin.webcast.UserInfoSerializer.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        str1_ = 0L;

        id_ = 0L;

        name_ = "";

        gender_ = 0;

        if (headimgBuilder_ == null) {
          headimg_ = null;
        } else {
          headimg_ = null;
          headimgBuilder_ = null;
        }
        if (uObjBuilder_ == null) {
          uObj_ = null;
        } else {
          uObj_ = null;
          uObjBuilder_ = null;
        }
        idStr_ = "";

        secUid_ = "";

        authorizationInfo_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.douyin.webcast.UserInfoSerializer.internal_static_com_douyin_webcast_proto_UserInfo_descriptor;
      }

      @java.lang.Override
      public com.douyin.webcast.UserInfoSerializer.UserInfo getDefaultInstanceForType() {
        return com.douyin.webcast.UserInfoSerializer.UserInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.douyin.webcast.UserInfoSerializer.UserInfo build() {
        com.douyin.webcast.UserInfoSerializer.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.douyin.webcast.UserInfoSerializer.UserInfo buildPartial() {
        com.douyin.webcast.UserInfoSerializer.UserInfo result = new com.douyin.webcast.UserInfoSerializer.UserInfo(this);
        result.str1_ = str1_;
        result.id_ = id_;
        result.name_ = name_;
        result.gender_ = gender_;
        if (headimgBuilder_ == null) {
          result.headimg_ = headimg_;
        } else {
          result.headimg_ = headimgBuilder_.build();
        }
        if (uObjBuilder_ == null) {
          result.uObj_ = uObj_;
        } else {
          result.uObj_ = uObjBuilder_.build();
        }
        result.idStr_ = idStr_;
        result.secUid_ = secUid_;
        result.authorizationInfo_ = authorizationInfo_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.douyin.webcast.UserInfoSerializer.UserInfo) {
          return mergeFrom((com.douyin.webcast.UserInfoSerializer.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.douyin.webcast.UserInfoSerializer.UserInfo other) {
        if (other == com.douyin.webcast.UserInfoSerializer.UserInfo.getDefaultInstance()) return this;
        if (other.getStr1() != 0L) {
          setStr1(other.getStr1());
        }
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getGender() != 0) {
          setGender(other.getGender());
        }
        if (other.hasHeadimg()) {
          mergeHeadimg(other.getHeadimg());
        }
        if (other.hasUObj()) {
          mergeUObj(other.getUObj());
        }
        if (!other.getIdStr().isEmpty()) {
          idStr_ = other.idStr_;
          onChanged();
        }
        if (!other.getSecUid().isEmpty()) {
          secUid_ = other.secUid_;
          onChanged();
        }
        if (other.getAuthorizationInfo() != 0) {
          setAuthorizationInfo(other.getAuthorizationInfo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.douyin.webcast.UserInfoSerializer.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.douyin.webcast.UserInfoSerializer.UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long str1_ ;
      /**
       * <code>int64 str1 = 1;</code>
       * @return The str1.
       */
      @java.lang.Override
      public long getStr1() {
        return str1_;
      }
      /**
       * <code>int64 str1 = 1;</code>
       * @param value The str1 to set.
       * @return This builder for chaining.
       */
      public Builder setStr1(long value) {
        
        str1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 str1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStr1() {
        
        str1_ = 0L;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *          用户id，短数字类型
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *          用户id，短数字类型
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *          用户id，短数字类型
       * </pre>
       *
       * <code>int64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ ;
      /**
       * <code>int32 gender = 4;</code>
       * @return The gender.
       */
      @java.lang.Override
      public int getGender() {
        return gender_;
      }
      /**
       * <code>int32 gender = 4;</code>
       * @param value The gender to set.
       * @return This builder for chaining.
       */
      public Builder setGender(int value) {
        
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 gender = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private com.douyin.webcast.CoverInfoSerializer.CoverInfo headimg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.CoverInfoSerializer.CoverInfo, com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder, com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder> headimgBuilder_;
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       * @return Whether the headimg field is set.
       */
      public boolean hasHeadimg() {
        return headimgBuilder_ != null || headimg_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       * @return The headimg.
       */
      public com.douyin.webcast.CoverInfoSerializer.CoverInfo getHeadimg() {
        if (headimgBuilder_ == null) {
          return headimg_ == null ? com.douyin.webcast.CoverInfoSerializer.CoverInfo.getDefaultInstance() : headimg_;
        } else {
          return headimgBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      public Builder setHeadimg(com.douyin.webcast.CoverInfoSerializer.CoverInfo value) {
        if (headimgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          headimg_ = value;
          onChanged();
        } else {
          headimgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      public Builder setHeadimg(
          com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder builderForValue) {
        if (headimgBuilder_ == null) {
          headimg_ = builderForValue.build();
          onChanged();
        } else {
          headimgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      public Builder mergeHeadimg(com.douyin.webcast.CoverInfoSerializer.CoverInfo value) {
        if (headimgBuilder_ == null) {
          if (headimg_ != null) {
            headimg_ =
              com.douyin.webcast.CoverInfoSerializer.CoverInfo.newBuilder(headimg_).mergeFrom(value).buildPartial();
          } else {
            headimg_ = value;
          }
          onChanged();
        } else {
          headimgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      public Builder clearHeadimg() {
        if (headimgBuilder_ == null) {
          headimg_ = null;
          onChanged();
        } else {
          headimg_ = null;
          headimgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      public com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder getHeadimgBuilder() {
        
        onChanged();
        return getHeadimgFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      public com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder getHeadimgOrBuilder() {
        if (headimgBuilder_ != null) {
          return headimgBuilder_.getMessageOrBuilder();
        } else {
          return headimg_ == null ?
              com.douyin.webcast.CoverInfoSerializer.CoverInfo.getDefaultInstance() : headimg_;
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.CoverInfo headimg = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.CoverInfoSerializer.CoverInfo, com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder, com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder> 
          getHeadimgFieldBuilder() {
        if (headimgBuilder_ == null) {
          headimgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.douyin.webcast.CoverInfoSerializer.CoverInfo, com.douyin.webcast.CoverInfoSerializer.CoverInfo.Builder, com.douyin.webcast.CoverInfoSerializer.CoverInfoOrBuilder>(
                  getHeadimg(),
                  getParentForChildren(),
                  isClean());
          headimg_ = null;
        }
        return headimgBuilder_;
      }

      private com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 uObj_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder> uObjBuilder_;
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       * @return Whether the uObj field is set.
       */
      public boolean hasUObj() {
        return uObjBuilder_ != null || uObj_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       * @return The uObj.
       */
      public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 getUObj() {
        if (uObjBuilder_ == null) {
          return uObj_ == null ? com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.getDefaultInstance() : uObj_;
        } else {
          return uObjBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      public Builder setUObj(com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 value) {
        if (uObjBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          uObj_ = value;
          onChanged();
        } else {
          uObjBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      public Builder setUObj(
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder builderForValue) {
        if (uObjBuilder_ == null) {
          uObj_ = builderForValue.build();
          onChanged();
        } else {
          uObjBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      public Builder mergeUObj(com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22 value) {
        if (uObjBuilder_ == null) {
          if (uObj_ != null) {
            uObj_ =
              com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.newBuilder(uObj_).mergeFrom(value).buildPartial();
          } else {
            uObj_ = value;
          }
          onChanged();
        } else {
          uObjBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      public Builder clearUObj() {
        if (uObjBuilder_ == null) {
          uObj_ = null;
          onChanged();
        } else {
          uObj_ = null;
          uObjBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder getUObjBuilder() {
        
        onChanged();
        return getUObjFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      public com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder getUObjOrBuilder() {
        if (uObjBuilder_ != null) {
          return uObjBuilder_.getMessageOrBuilder();
        } else {
          return uObj_ == null ?
              com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.getDefaultInstance() : uObj_;
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo.U_Obj22 u_obj = 22;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder> 
          getUObjFieldBuilder() {
        if (uObjBuilder_ == null) {
          uObjBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22.Builder, com.douyin.webcast.UserInfoSerializer.UserInfo.U_Obj22OrBuilder>(
                  getUObj(),
                  getParentForChildren(),
                  isClean());
          uObj_ = null;
        }
        return uObjBuilder_;
      }

      private java.lang.Object idStr_ = "";
      /**
       * <code>string id_str = 38;</code>
       * @return The idStr.
       */
      public java.lang.String getIdStr() {
        java.lang.Object ref = idStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idStr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id_str = 38;</code>
       * @return The bytes for idStr.
       */
      public com.google.protobuf.ByteString
          getIdStrBytes() {
        java.lang.Object ref = idStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id_str = 38;</code>
       * @param value The idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id_str = 38;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdStr() {
        
        idStr_ = getDefaultInstance().getIdStr();
        onChanged();
        return this;
      }
      /**
       * <code>string id_str = 38;</code>
       * @param value The bytes for idStr to set.
       * @return This builder for chaining.
       */
      public Builder setIdStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idStr_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object secUid_ = "";
      /**
       * <pre>
       *          加密的用户id，访问其它接口时的必备参数
       * </pre>
       *
       * <code>string sec_uid = 46;</code>
       * @return The secUid.
       */
      public java.lang.String getSecUid() {
        java.lang.Object ref = secUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *          加密的用户id，访问其它接口时的必备参数
       * </pre>
       *
       * <code>string sec_uid = 46;</code>
       * @return The bytes for secUid.
       */
      public com.google.protobuf.ByteString
          getSecUidBytes() {
        java.lang.Object ref = secUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *          加密的用户id，访问其它接口时的必备参数
       * </pre>
       *
       * <code>string sec_uid = 46;</code>
       * @param value The secUid to set.
       * @return This builder for chaining.
       */
      public Builder setSecUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *          加密的用户id，访问其它接口时的必备参数
       * </pre>
       *
       * <code>string sec_uid = 46;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecUid() {
        
        secUid_ = getDefaultInstance().getSecUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *          加密的用户id，访问其它接口时的必备参数
       * </pre>
       *
       * <code>string sec_uid = 46;</code>
       * @param value The bytes for secUid to set.
       * @return This builder for chaining.
       */
      public Builder setSecUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secUid_ = value;
        onChanged();
        return this;
      }

      private int authorizationInfo_ ;
      /**
       * <code>int32 authorization_info = 54;</code>
       * @return The authorizationInfo.
       */
      @java.lang.Override
      public int getAuthorizationInfo() {
        return authorizationInfo_;
      }
      /**
       * <code>int32 authorization_info = 54;</code>
       * @param value The authorizationInfo to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorizationInfo(int value) {
        
        authorizationInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 authorization_info = 54;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthorizationInfo() {
        
        authorizationInfo_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.UserInfo)
    }

    // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.UserInfo)
    private static final com.douyin.webcast.UserInfoSerializer.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.douyin.webcast.UserInfoSerializer.UserInfo();
    }

    public static com.douyin.webcast.UserInfoSerializer.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      @java.lang.Override
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.douyin.webcast.UserInfoSerializer.UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_UserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016UserInfo.proto\022\030com.douyin.webcast.pro" +
      "to\032\017CoverInfo.proto\"\237\002\n\010UserInfo\022\014\n\004str1" +
      "\030\001 \001(\003\022\n\n\002id\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\016\n\006gend" +
      "er\030\004 \001(\005\0224\n\007headimg\030\t \001(\0132#.com.douyin.w" +
      "ebcast.proto.CoverInfo\0229\n\005u_obj\030\026 \001(\0132*." +
      "com.douyin.webcast.proto.UserInfo.U_Obj2" +
      "2\022\016\n\006id_str\030& \001(\t\022\017\n\007sec_uid\030. \001(\t\022\032\n\022au" +
      "thorization_info\0306 \001(\005\032-\n\007U_Obj22\022\n\n\002o1\030" +
      "\001 \001(\005\022\n\n\002o2\030\002 \001(\005\022\n\n\002o3\030\003 \001(\005B(\n\022com.dou" +
      "yin.webcastB\022UserInfoSerializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.douyin.webcast.CoverInfoSerializer.getDescriptor(),
        });
    internal_static_com_douyin_webcast_proto_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_douyin_webcast_proto_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_UserInfo_descriptor,
        new java.lang.String[] { "Str1", "Id", "Name", "Gender", "Headimg", "UObj", "IdStr", "SecUid", "AuthorizationInfo", });
    internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_descriptor =
      internal_static_com_douyin_webcast_proto_UserInfo_descriptor.getNestedTypes().get(0);
    internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_UserInfo_U_Obj22_descriptor,
        new java.lang.String[] { "O1", "O2", "O3", });
    com.douyin.webcast.CoverInfoSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
