// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebcastGiftMessage.proto

package com.douyin.webcast;

public final class WebcastGiftMessageSerializer {
  private WebcastGiftMessageSerializer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WebcastGiftMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.WebcastGiftMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
     * @return The body.
     */
    com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody getBody();
    /**
     * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
     */
    com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code com.douyin.webcast.proto.WebcastGiftMessage}
   */
  public static final class WebcastGiftMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.WebcastGiftMessage)
      WebcastGiftMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebcastGiftMessage.newBuilder() to construct.
    private WebcastGiftMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebcastGiftMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebcastGiftMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WebcastGiftMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.class, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.Builder.class);
    }

    public interface WebcastGiftMessageBodyOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
       * @return Whether the timeInfo field is set.
       */
      boolean hasTimeInfo();
      /**
       * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
       * @return The timeInfo.
       */
      com.douyin.webcast.TimeInfoSerializer.TimeInfo getTimeInfo();
      /**
       * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
       */
      com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder getTimeInfoOrBuilder();

      /**
       * <code>int32 gift_bofy_2 = 2;</code>
       * @return The giftBofy2.
       */
      int getGiftBofy2();

      /**
       * <code>int64 gift_body_3 = 3;</code>
       * @return The giftBody3.
       */
      long getGiftBody3();

      /**
       * <code>int32 gift_body_4 = 4;</code>
       * @return The giftBody4.
       */
      int getGiftBody4();

      /**
       * <pre>
       *    送礼物数量
       * </pre>
       *
       * <code>int32 gift_count = 5;</code>
       * @return The giftCount.
       */
      int getGiftCount();

      /**
       * <pre>
       *    送礼物数量
       * </pre>
       *
       * <code>int32 gift_body_6 = 6;</code>
       * @return The giftBody6.
       */
      int getGiftBody6();

      /**
       * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
       * @return Whether the userInfo field is set.
       */
      boolean hasUserInfo();
      /**
       * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
       * @return The userInfo.
       */
      com.douyin.webcast.UserInfoSerializer.UserInfo getUserInfo();
      /**
       * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
       */
      com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder getUserInfoOrBuilder();

      /**
       * <code>int32 gift_body_9 = 9;</code>
       * @return The giftBody9.
       */
      int getGiftBody9();

      /**
       * <code>int64 timestamp = 11;</code>
       * @return The timestamp.
       */
      long getTimestamp();

      /**
       * <code>int32 gift_body_13 = 13;</code>
       * @return The giftBody13.
       */
      int getGiftBody13();

      /**
       * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
       * @return Whether the giftDetailsInfo field is set.
       */
      boolean hasGiftDetailsInfo();
      /**
       * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
       * @return The giftDetailsInfo.
       */
      com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo getGiftDetailsInfo();
      /**
       * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
       */
      com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfoOrBuilder getGiftDetailsInfoOrBuilder();

      /**
       * <pre>
       *    string gift_body_19=19;
       * </pre>
       *
       * <code>string gift_body_16 = 16;</code>
       * @return The giftBody16.
       */
      java.lang.String getGiftBody16();
      /**
       * <pre>
       *    string gift_body_19=19;
       * </pre>
       *
       * <code>string gift_body_16 = 16;</code>
       * @return The bytes for giftBody16.
       */
      com.google.protobuf.ByteString
          getGiftBody16Bytes();
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody}
     */
    public static final class WebcastGiftMessageBody extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody)
        WebcastGiftMessageBodyOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use WebcastGiftMessageBody.newBuilder() to construct.
      private WebcastGiftMessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private WebcastGiftMessageBody() {
        giftBody16_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new WebcastGiftMessageBody();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private WebcastGiftMessageBody(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder subBuilder = null;
                if (timeInfo_ != null) {
                  subBuilder = timeInfo_.toBuilder();
                }
                timeInfo_ = input.readMessage(com.douyin.webcast.TimeInfoSerializer.TimeInfo.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(timeInfo_);
                  timeInfo_ = subBuilder.buildPartial();
                }

                break;
              }
              case 16: {

                giftBofy2_ = input.readInt32();
                break;
              }
              case 24: {

                giftBody3_ = input.readInt64();
                break;
              }
              case 32: {

                giftBody4_ = input.readInt32();
                break;
              }
              case 40: {

                giftCount_ = input.readInt32();
                break;
              }
              case 48: {

                giftBody6_ = input.readInt32();
                break;
              }
              case 58: {
                com.douyin.webcast.UserInfoSerializer.UserInfo.Builder subBuilder = null;
                if (userInfo_ != null) {
                  subBuilder = userInfo_.toBuilder();
                }
                userInfo_ = input.readMessage(com.douyin.webcast.UserInfoSerializer.UserInfo.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(userInfo_);
                  userInfo_ = subBuilder.buildPartial();
                }

                break;
              }
              case 72: {

                giftBody9_ = input.readInt32();
                break;
              }
              case 88: {

                timestamp_ = input.readInt64();
                break;
              }
              case 104: {

                giftBody13_ = input.readInt32();
                break;
              }
              case 122: {
                com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.Builder subBuilder = null;
                if (giftDetailsInfo_ != null) {
                  subBuilder = giftDetailsInfo_.toBuilder();
                }
                giftDetailsInfo_ = input.readMessage(com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(giftDetailsInfo_);
                  giftDetailsInfo_ = subBuilder.buildPartial();
                }

                break;
              }
              case 130: {
                java.lang.String s = input.readStringRequireUtf8();

                giftBody16_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.class, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder.class);
      }

      public static final int TIMEINFO_FIELD_NUMBER = 1;
      private com.douyin.webcast.TimeInfoSerializer.TimeInfo timeInfo_;
      /**
       * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
       * @return Whether the timeInfo field is set.
       */
      @java.lang.Override
      public boolean hasTimeInfo() {
        return timeInfo_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
       * @return The timeInfo.
       */
      @java.lang.Override
      public com.douyin.webcast.TimeInfoSerializer.TimeInfo getTimeInfo() {
        return timeInfo_ == null ? com.douyin.webcast.TimeInfoSerializer.TimeInfo.getDefaultInstance() : timeInfo_;
      }
      /**
       * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
       */
      @java.lang.Override
      public com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder getTimeInfoOrBuilder() {
        return getTimeInfo();
      }

      public static final int GIFT_BOFY_2_FIELD_NUMBER = 2;
      private int giftBofy2_;
      /**
       * <code>int32 gift_bofy_2 = 2;</code>
       * @return The giftBofy2.
       */
      @java.lang.Override
      public int getGiftBofy2() {
        return giftBofy2_;
      }

      public static final int GIFT_BODY_3_FIELD_NUMBER = 3;
      private long giftBody3_;
      /**
       * <code>int64 gift_body_3 = 3;</code>
       * @return The giftBody3.
       */
      @java.lang.Override
      public long getGiftBody3() {
        return giftBody3_;
      }

      public static final int GIFT_BODY_4_FIELD_NUMBER = 4;
      private int giftBody4_;
      /**
       * <code>int32 gift_body_4 = 4;</code>
       * @return The giftBody4.
       */
      @java.lang.Override
      public int getGiftBody4() {
        return giftBody4_;
      }

      public static final int GIFT_COUNT_FIELD_NUMBER = 5;
      private int giftCount_;
      /**
       * <pre>
       *    送礼物数量
       * </pre>
       *
       * <code>int32 gift_count = 5;</code>
       * @return The giftCount.
       */
      @java.lang.Override
      public int getGiftCount() {
        return giftCount_;
      }

      public static final int GIFT_BODY_6_FIELD_NUMBER = 6;
      private int giftBody6_;
      /**
       * <pre>
       *    送礼物数量
       * </pre>
       *
       * <code>int32 gift_body_6 = 6;</code>
       * @return The giftBody6.
       */
      @java.lang.Override
      public int getGiftBody6() {
        return giftBody6_;
      }

      public static final int USERINFO_FIELD_NUMBER = 7;
      private com.douyin.webcast.UserInfoSerializer.UserInfo userInfo_;
      /**
       * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
       * @return Whether the userInfo field is set.
       */
      @java.lang.Override
      public boolean hasUserInfo() {
        return userInfo_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
       * @return The userInfo.
       */
      @java.lang.Override
      public com.douyin.webcast.UserInfoSerializer.UserInfo getUserInfo() {
        return userInfo_ == null ? com.douyin.webcast.UserInfoSerializer.UserInfo.getDefaultInstance() : userInfo_;
      }
      /**
       * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
       */
      @java.lang.Override
      public com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder getUserInfoOrBuilder() {
        return getUserInfo();
      }

      public static final int GIFT_BODY_9_FIELD_NUMBER = 9;
      private int giftBody9_;
      /**
       * <code>int32 gift_body_9 = 9;</code>
       * @return The giftBody9.
       */
      @java.lang.Override
      public int getGiftBody9() {
        return giftBody9_;
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 11;
      private long timestamp_;
      /**
       * <code>int64 timestamp = 11;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }

      public static final int GIFT_BODY_13_FIELD_NUMBER = 13;
      private int giftBody13_;
      /**
       * <code>int32 gift_body_13 = 13;</code>
       * @return The giftBody13.
       */
      @java.lang.Override
      public int getGiftBody13() {
        return giftBody13_;
      }

      public static final int GIFTDETAILSINFO_FIELD_NUMBER = 15;
      private com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo giftDetailsInfo_;
      /**
       * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
       * @return Whether the giftDetailsInfo field is set.
       */
      @java.lang.Override
      public boolean hasGiftDetailsInfo() {
        return giftDetailsInfo_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
       * @return The giftDetailsInfo.
       */
      @java.lang.Override
      public com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo getGiftDetailsInfo() {
        return giftDetailsInfo_ == null ? com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.getDefaultInstance() : giftDetailsInfo_;
      }
      /**
       * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
       */
      @java.lang.Override
      public com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfoOrBuilder getGiftDetailsInfoOrBuilder() {
        return getGiftDetailsInfo();
      }

      public static final int GIFT_BODY_16_FIELD_NUMBER = 16;
      private volatile java.lang.Object giftBody16_;
      /**
       * <pre>
       *    string gift_body_19=19;
       * </pre>
       *
       * <code>string gift_body_16 = 16;</code>
       * @return The giftBody16.
       */
      @java.lang.Override
      public java.lang.String getGiftBody16() {
        java.lang.Object ref = giftBody16_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          giftBody16_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *    string gift_body_19=19;
       * </pre>
       *
       * <code>string gift_body_16 = 16;</code>
       * @return The bytes for giftBody16.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getGiftBody16Bytes() {
        java.lang.Object ref = giftBody16_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          giftBody16_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (timeInfo_ != null) {
          output.writeMessage(1, getTimeInfo());
        }
        if (giftBofy2_ != 0) {
          output.writeInt32(2, giftBofy2_);
        }
        if (giftBody3_ != 0L) {
          output.writeInt64(3, giftBody3_);
        }
        if (giftBody4_ != 0) {
          output.writeInt32(4, giftBody4_);
        }
        if (giftCount_ != 0) {
          output.writeInt32(5, giftCount_);
        }
        if (giftBody6_ != 0) {
          output.writeInt32(6, giftBody6_);
        }
        if (userInfo_ != null) {
          output.writeMessage(7, getUserInfo());
        }
        if (giftBody9_ != 0) {
          output.writeInt32(9, giftBody9_);
        }
        if (timestamp_ != 0L) {
          output.writeInt64(11, timestamp_);
        }
        if (giftBody13_ != 0) {
          output.writeInt32(13, giftBody13_);
        }
        if (giftDetailsInfo_ != null) {
          output.writeMessage(15, getGiftDetailsInfo());
        }
        if (!getGiftBody16Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 16, giftBody16_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (timeInfo_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getTimeInfo());
        }
        if (giftBofy2_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, giftBofy2_);
        }
        if (giftBody3_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, giftBody3_);
        }
        if (giftBody4_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, giftBody4_);
        }
        if (giftCount_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, giftCount_);
        }
        if (giftBody6_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, giftBody6_);
        }
        if (userInfo_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, getUserInfo());
        }
        if (giftBody9_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(9, giftBody9_);
        }
        if (timestamp_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(11, timestamp_);
        }
        if (giftBody13_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(13, giftBody13_);
        }
        if (giftDetailsInfo_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(15, getGiftDetailsInfo());
        }
        if (!getGiftBody16Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, giftBody16_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody)) {
          return super.equals(obj);
        }
        com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody other = (com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody) obj;

        if (hasTimeInfo() != other.hasTimeInfo()) return false;
        if (hasTimeInfo()) {
          if (!getTimeInfo()
              .equals(other.getTimeInfo())) return false;
        }
        if (getGiftBofy2()
            != other.getGiftBofy2()) return false;
        if (getGiftBody3()
            != other.getGiftBody3()) return false;
        if (getGiftBody4()
            != other.getGiftBody4()) return false;
        if (getGiftCount()
            != other.getGiftCount()) return false;
        if (getGiftBody6()
            != other.getGiftBody6()) return false;
        if (hasUserInfo() != other.hasUserInfo()) return false;
        if (hasUserInfo()) {
          if (!getUserInfo()
              .equals(other.getUserInfo())) return false;
        }
        if (getGiftBody9()
            != other.getGiftBody9()) return false;
        if (getTimestamp()
            != other.getTimestamp()) return false;
        if (getGiftBody13()
            != other.getGiftBody13()) return false;
        if (hasGiftDetailsInfo() != other.hasGiftDetailsInfo()) return false;
        if (hasGiftDetailsInfo()) {
          if (!getGiftDetailsInfo()
              .equals(other.getGiftDetailsInfo())) return false;
        }
        if (!getGiftBody16()
            .equals(other.getGiftBody16())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasTimeInfo()) {
          hash = (37 * hash) + TIMEINFO_FIELD_NUMBER;
          hash = (53 * hash) + getTimeInfo().hashCode();
        }
        hash = (37 * hash) + GIFT_BOFY_2_FIELD_NUMBER;
        hash = (53 * hash) + getGiftBofy2();
        hash = (37 * hash) + GIFT_BODY_3_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getGiftBody3());
        hash = (37 * hash) + GIFT_BODY_4_FIELD_NUMBER;
        hash = (53 * hash) + getGiftBody4();
        hash = (37 * hash) + GIFT_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getGiftCount();
        hash = (37 * hash) + GIFT_BODY_6_FIELD_NUMBER;
        hash = (53 * hash) + getGiftBody6();
        if (hasUserInfo()) {
          hash = (37 * hash) + USERINFO_FIELD_NUMBER;
          hash = (53 * hash) + getUserInfo().hashCode();
        }
        hash = (37 * hash) + GIFT_BODY_9_FIELD_NUMBER;
        hash = (53 * hash) + getGiftBody9();
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTimestamp());
        hash = (37 * hash) + GIFT_BODY_13_FIELD_NUMBER;
        hash = (53 * hash) + getGiftBody13();
        if (hasGiftDetailsInfo()) {
          hash = (37 * hash) + GIFTDETAILSINFO_FIELD_NUMBER;
          hash = (53 * hash) + getGiftDetailsInfo().hashCode();
        }
        hash = (37 * hash) + GIFT_BODY_16_FIELD_NUMBER;
        hash = (53 * hash) + getGiftBody16().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody)
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.class, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder.class);
        }

        // Construct using com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (timeInfoBuilder_ == null) {
            timeInfo_ = null;
          } else {
            timeInfo_ = null;
            timeInfoBuilder_ = null;
          }
          giftBofy2_ = 0;

          giftBody3_ = 0L;

          giftBody4_ = 0;

          giftCount_ = 0;

          giftBody6_ = 0;

          if (userInfoBuilder_ == null) {
            userInfo_ = null;
          } else {
            userInfo_ = null;
            userInfoBuilder_ = null;
          }
          giftBody9_ = 0;

          timestamp_ = 0L;

          giftBody13_ = 0;

          if (giftDetailsInfoBuilder_ == null) {
            giftDetailsInfo_ = null;
          } else {
            giftDetailsInfo_ = null;
            giftDetailsInfoBuilder_ = null;
          }
          giftBody16_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_descriptor;
        }

        @java.lang.Override
        public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody getDefaultInstanceForType() {
          return com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.getDefaultInstance();
        }

        @java.lang.Override
        public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody build() {
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody buildPartial() {
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody result = new com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody(this);
          if (timeInfoBuilder_ == null) {
            result.timeInfo_ = timeInfo_;
          } else {
            result.timeInfo_ = timeInfoBuilder_.build();
          }
          result.giftBofy2_ = giftBofy2_;
          result.giftBody3_ = giftBody3_;
          result.giftBody4_ = giftBody4_;
          result.giftCount_ = giftCount_;
          result.giftBody6_ = giftBody6_;
          if (userInfoBuilder_ == null) {
            result.userInfo_ = userInfo_;
          } else {
            result.userInfo_ = userInfoBuilder_.build();
          }
          result.giftBody9_ = giftBody9_;
          result.timestamp_ = timestamp_;
          result.giftBody13_ = giftBody13_;
          if (giftDetailsInfoBuilder_ == null) {
            result.giftDetailsInfo_ = giftDetailsInfo_;
          } else {
            result.giftDetailsInfo_ = giftDetailsInfoBuilder_.build();
          }
          result.giftBody16_ = giftBody16_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody) {
            return mergeFrom((com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody other) {
          if (other == com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.getDefaultInstance()) return this;
          if (other.hasTimeInfo()) {
            mergeTimeInfo(other.getTimeInfo());
          }
          if (other.getGiftBofy2() != 0) {
            setGiftBofy2(other.getGiftBofy2());
          }
          if (other.getGiftBody3() != 0L) {
            setGiftBody3(other.getGiftBody3());
          }
          if (other.getGiftBody4() != 0) {
            setGiftBody4(other.getGiftBody4());
          }
          if (other.getGiftCount() != 0) {
            setGiftCount(other.getGiftCount());
          }
          if (other.getGiftBody6() != 0) {
            setGiftBody6(other.getGiftBody6());
          }
          if (other.hasUserInfo()) {
            mergeUserInfo(other.getUserInfo());
          }
          if (other.getGiftBody9() != 0) {
            setGiftBody9(other.getGiftBody9());
          }
          if (other.getTimestamp() != 0L) {
            setTimestamp(other.getTimestamp());
          }
          if (other.getGiftBody13() != 0) {
            setGiftBody13(other.getGiftBody13());
          }
          if (other.hasGiftDetailsInfo()) {
            mergeGiftDetailsInfo(other.getGiftDetailsInfo());
          }
          if (!other.getGiftBody16().isEmpty()) {
            giftBody16_ = other.giftBody16_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.douyin.webcast.TimeInfoSerializer.TimeInfo timeInfo_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.douyin.webcast.TimeInfoSerializer.TimeInfo, com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder, com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder> timeInfoBuilder_;
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         * @return Whether the timeInfo field is set.
         */
        public boolean hasTimeInfo() {
          return timeInfoBuilder_ != null || timeInfo_ != null;
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         * @return The timeInfo.
         */
        public com.douyin.webcast.TimeInfoSerializer.TimeInfo getTimeInfo() {
          if (timeInfoBuilder_ == null) {
            return timeInfo_ == null ? com.douyin.webcast.TimeInfoSerializer.TimeInfo.getDefaultInstance() : timeInfo_;
          } else {
            return timeInfoBuilder_.getMessage();
          }
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        public Builder setTimeInfo(com.douyin.webcast.TimeInfoSerializer.TimeInfo value) {
          if (timeInfoBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            timeInfo_ = value;
            onChanged();
          } else {
            timeInfoBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        public Builder setTimeInfo(
            com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder builderForValue) {
          if (timeInfoBuilder_ == null) {
            timeInfo_ = builderForValue.build();
            onChanged();
          } else {
            timeInfoBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        public Builder mergeTimeInfo(com.douyin.webcast.TimeInfoSerializer.TimeInfo value) {
          if (timeInfoBuilder_ == null) {
            if (timeInfo_ != null) {
              timeInfo_ =
                com.douyin.webcast.TimeInfoSerializer.TimeInfo.newBuilder(timeInfo_).mergeFrom(value).buildPartial();
            } else {
              timeInfo_ = value;
            }
            onChanged();
          } else {
            timeInfoBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        public Builder clearTimeInfo() {
          if (timeInfoBuilder_ == null) {
            timeInfo_ = null;
            onChanged();
          } else {
            timeInfo_ = null;
            timeInfoBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        public com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder getTimeInfoBuilder() {
          
          onChanged();
          return getTimeInfoFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        public com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder getTimeInfoOrBuilder() {
          if (timeInfoBuilder_ != null) {
            return timeInfoBuilder_.getMessageOrBuilder();
          } else {
            return timeInfo_ == null ?
                com.douyin.webcast.TimeInfoSerializer.TimeInfo.getDefaultInstance() : timeInfo_;
          }
        }
        /**
         * <code>.com.douyin.webcast.proto.TimeInfo timeInfo = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.douyin.webcast.TimeInfoSerializer.TimeInfo, com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder, com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder> 
            getTimeInfoFieldBuilder() {
          if (timeInfoBuilder_ == null) {
            timeInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.douyin.webcast.TimeInfoSerializer.TimeInfo, com.douyin.webcast.TimeInfoSerializer.TimeInfo.Builder, com.douyin.webcast.TimeInfoSerializer.TimeInfoOrBuilder>(
                    getTimeInfo(),
                    getParentForChildren(),
                    isClean());
            timeInfo_ = null;
          }
          return timeInfoBuilder_;
        }

        private int giftBofy2_ ;
        /**
         * <code>int32 gift_bofy_2 = 2;</code>
         * @return The giftBofy2.
         */
        @java.lang.Override
        public int getGiftBofy2() {
          return giftBofy2_;
        }
        /**
         * <code>int32 gift_bofy_2 = 2;</code>
         * @param value The giftBofy2 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBofy2(int value) {
          
          giftBofy2_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 gift_bofy_2 = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBofy2() {
          
          giftBofy2_ = 0;
          onChanged();
          return this;
        }

        private long giftBody3_ ;
        /**
         * <code>int64 gift_body_3 = 3;</code>
         * @return The giftBody3.
         */
        @java.lang.Override
        public long getGiftBody3() {
          return giftBody3_;
        }
        /**
         * <code>int64 gift_body_3 = 3;</code>
         * @param value The giftBody3 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody3(long value) {
          
          giftBody3_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 gift_body_3 = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBody3() {
          
          giftBody3_ = 0L;
          onChanged();
          return this;
        }

        private int giftBody4_ ;
        /**
         * <code>int32 gift_body_4 = 4;</code>
         * @return The giftBody4.
         */
        @java.lang.Override
        public int getGiftBody4() {
          return giftBody4_;
        }
        /**
         * <code>int32 gift_body_4 = 4;</code>
         * @param value The giftBody4 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody4(int value) {
          
          giftBody4_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 gift_body_4 = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBody4() {
          
          giftBody4_ = 0;
          onChanged();
          return this;
        }

        private int giftCount_ ;
        /**
         * <pre>
         *    送礼物数量
         * </pre>
         *
         * <code>int32 gift_count = 5;</code>
         * @return The giftCount.
         */
        @java.lang.Override
        public int getGiftCount() {
          return giftCount_;
        }
        /**
         * <pre>
         *    送礼物数量
         * </pre>
         *
         * <code>int32 gift_count = 5;</code>
         * @param value The giftCount to set.
         * @return This builder for chaining.
         */
        public Builder setGiftCount(int value) {
          
          giftCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *    送礼物数量
         * </pre>
         *
         * <code>int32 gift_count = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftCount() {
          
          giftCount_ = 0;
          onChanged();
          return this;
        }

        private int giftBody6_ ;
        /**
         * <pre>
         *    送礼物数量
         * </pre>
         *
         * <code>int32 gift_body_6 = 6;</code>
         * @return The giftBody6.
         */
        @java.lang.Override
        public int getGiftBody6() {
          return giftBody6_;
        }
        /**
         * <pre>
         *    送礼物数量
         * </pre>
         *
         * <code>int32 gift_body_6 = 6;</code>
         * @param value The giftBody6 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody6(int value) {
          
          giftBody6_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *    送礼物数量
         * </pre>
         *
         * <code>int32 gift_body_6 = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBody6() {
          
          giftBody6_ = 0;
          onChanged();
          return this;
        }

        private com.douyin.webcast.UserInfoSerializer.UserInfo userInfo_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.douyin.webcast.UserInfoSerializer.UserInfo, com.douyin.webcast.UserInfoSerializer.UserInfo.Builder, com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder> userInfoBuilder_;
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         * @return Whether the userInfo field is set.
         */
        public boolean hasUserInfo() {
          return userInfoBuilder_ != null || userInfo_ != null;
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         * @return The userInfo.
         */
        public com.douyin.webcast.UserInfoSerializer.UserInfo getUserInfo() {
          if (userInfoBuilder_ == null) {
            return userInfo_ == null ? com.douyin.webcast.UserInfoSerializer.UserInfo.getDefaultInstance() : userInfo_;
          } else {
            return userInfoBuilder_.getMessage();
          }
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        public Builder setUserInfo(com.douyin.webcast.UserInfoSerializer.UserInfo value) {
          if (userInfoBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            userInfo_ = value;
            onChanged();
          } else {
            userInfoBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        public Builder setUserInfo(
            com.douyin.webcast.UserInfoSerializer.UserInfo.Builder builderForValue) {
          if (userInfoBuilder_ == null) {
            userInfo_ = builderForValue.build();
            onChanged();
          } else {
            userInfoBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        public Builder mergeUserInfo(com.douyin.webcast.UserInfoSerializer.UserInfo value) {
          if (userInfoBuilder_ == null) {
            if (userInfo_ != null) {
              userInfo_ =
                com.douyin.webcast.UserInfoSerializer.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
            } else {
              userInfo_ = value;
            }
            onChanged();
          } else {
            userInfoBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        public Builder clearUserInfo() {
          if (userInfoBuilder_ == null) {
            userInfo_ = null;
            onChanged();
          } else {
            userInfo_ = null;
            userInfoBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        public com.douyin.webcast.UserInfoSerializer.UserInfo.Builder getUserInfoBuilder() {
          
          onChanged();
          return getUserInfoFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        public com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder getUserInfoOrBuilder() {
          if (userInfoBuilder_ != null) {
            return userInfoBuilder_.getMessageOrBuilder();
          } else {
            return userInfo_ == null ?
                com.douyin.webcast.UserInfoSerializer.UserInfo.getDefaultInstance() : userInfo_;
          }
        }
        /**
         * <code>.com.douyin.webcast.proto.UserInfo userInfo = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.douyin.webcast.UserInfoSerializer.UserInfo, com.douyin.webcast.UserInfoSerializer.UserInfo.Builder, com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder> 
            getUserInfoFieldBuilder() {
          if (userInfoBuilder_ == null) {
            userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.douyin.webcast.UserInfoSerializer.UserInfo, com.douyin.webcast.UserInfoSerializer.UserInfo.Builder, com.douyin.webcast.UserInfoSerializer.UserInfoOrBuilder>(
                    getUserInfo(),
                    getParentForChildren(),
                    isClean());
            userInfo_ = null;
          }
          return userInfoBuilder_;
        }

        private int giftBody9_ ;
        /**
         * <code>int32 gift_body_9 = 9;</code>
         * @return The giftBody9.
         */
        @java.lang.Override
        public int getGiftBody9() {
          return giftBody9_;
        }
        /**
         * <code>int32 gift_body_9 = 9;</code>
         * @param value The giftBody9 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody9(int value) {
          
          giftBody9_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 gift_body_9 = 9;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBody9() {
          
          giftBody9_ = 0;
          onChanged();
          return this;
        }

        private long timestamp_ ;
        /**
         * <code>int64 timestamp = 11;</code>
         * @return The timestamp.
         */
        @java.lang.Override
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>int64 timestamp = 11;</code>
         * @param value The timestamp to set.
         * @return This builder for chaining.
         */
        public Builder setTimestamp(long value) {
          
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 timestamp = 11;</code>
         * @return This builder for chaining.
         */
        public Builder clearTimestamp() {
          
          timestamp_ = 0L;
          onChanged();
          return this;
        }

        private int giftBody13_ ;
        /**
         * <code>int32 gift_body_13 = 13;</code>
         * @return The giftBody13.
         */
        @java.lang.Override
        public int getGiftBody13() {
          return giftBody13_;
        }
        /**
         * <code>int32 gift_body_13 = 13;</code>
         * @param value The giftBody13 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody13(int value) {
          
          giftBody13_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 gift_body_13 = 13;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBody13() {
          
          giftBody13_ = 0;
          onChanged();
          return this;
        }

        private com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo giftDetailsInfo_;
        private com.google.protobuf.SingleFieldBuilderV3<
            com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo, com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.Builder, com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfoOrBuilder> giftDetailsInfoBuilder_;
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         * @return Whether the giftDetailsInfo field is set.
         */
        public boolean hasGiftDetailsInfo() {
          return giftDetailsInfoBuilder_ != null || giftDetailsInfo_ != null;
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         * @return The giftDetailsInfo.
         */
        public com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo getGiftDetailsInfo() {
          if (giftDetailsInfoBuilder_ == null) {
            return giftDetailsInfo_ == null ? com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.getDefaultInstance() : giftDetailsInfo_;
          } else {
            return giftDetailsInfoBuilder_.getMessage();
          }
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        public Builder setGiftDetailsInfo(com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo value) {
          if (giftDetailsInfoBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            giftDetailsInfo_ = value;
            onChanged();
          } else {
            giftDetailsInfoBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        public Builder setGiftDetailsInfo(
            com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.Builder builderForValue) {
          if (giftDetailsInfoBuilder_ == null) {
            giftDetailsInfo_ = builderForValue.build();
            onChanged();
          } else {
            giftDetailsInfoBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        public Builder mergeGiftDetailsInfo(com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo value) {
          if (giftDetailsInfoBuilder_ == null) {
            if (giftDetailsInfo_ != null) {
              giftDetailsInfo_ =
                com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.newBuilder(giftDetailsInfo_).mergeFrom(value).buildPartial();
            } else {
              giftDetailsInfo_ = value;
            }
            onChanged();
          } else {
            giftDetailsInfoBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        public Builder clearGiftDetailsInfo() {
          if (giftDetailsInfoBuilder_ == null) {
            giftDetailsInfo_ = null;
            onChanged();
          } else {
            giftDetailsInfo_ = null;
            giftDetailsInfoBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        public com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.Builder getGiftDetailsInfoBuilder() {
          
          onChanged();
          return getGiftDetailsInfoFieldBuilder().getBuilder();
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        public com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfoOrBuilder getGiftDetailsInfoOrBuilder() {
          if (giftDetailsInfoBuilder_ != null) {
            return giftDetailsInfoBuilder_.getMessageOrBuilder();
          } else {
            return giftDetailsInfo_ == null ?
                com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.getDefaultInstance() : giftDetailsInfo_;
          }
        }
        /**
         * <code>.com.douyin.webcast.proto.GiftDetailsInfo giftDetailsInfo = 15;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo, com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.Builder, com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfoOrBuilder> 
            getGiftDetailsInfoFieldBuilder() {
          if (giftDetailsInfoBuilder_ == null) {
            giftDetailsInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo, com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfo.Builder, com.douyin.webcast.GiftDetailsInfoSerializer.GiftDetailsInfoOrBuilder>(
                    getGiftDetailsInfo(),
                    getParentForChildren(),
                    isClean());
            giftDetailsInfo_ = null;
          }
          return giftDetailsInfoBuilder_;
        }

        private java.lang.Object giftBody16_ = "";
        /**
         * <pre>
         *    string gift_body_19=19;
         * </pre>
         *
         * <code>string gift_body_16 = 16;</code>
         * @return The giftBody16.
         */
        public java.lang.String getGiftBody16() {
          java.lang.Object ref = giftBody16_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            giftBody16_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *    string gift_body_19=19;
         * </pre>
         *
         * <code>string gift_body_16 = 16;</code>
         * @return The bytes for giftBody16.
         */
        public com.google.protobuf.ByteString
            getGiftBody16Bytes() {
          java.lang.Object ref = giftBody16_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            giftBody16_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *    string gift_body_19=19;
         * </pre>
         *
         * <code>string gift_body_16 = 16;</code>
         * @param value The giftBody16 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody16(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          giftBody16_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *    string gift_body_19=19;
         * </pre>
         *
         * <code>string gift_body_16 = 16;</code>
         * @return This builder for chaining.
         */
        public Builder clearGiftBody16() {
          
          giftBody16_ = getDefaultInstance().getGiftBody16();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *    string gift_body_19=19;
         * </pre>
         *
         * <code>string gift_body_16 = 16;</code>
         * @param value The bytes for giftBody16 to set.
         * @return This builder for chaining.
         */
        public Builder setGiftBody16Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          giftBody16_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody)
      }

      // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody)
      private static final com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody();
      }

      public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<WebcastGiftMessageBody>
          PARSER = new com.google.protobuf.AbstractParser<WebcastGiftMessageBody>() {
        @java.lang.Override
        public WebcastGiftMessageBody parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new WebcastGiftMessageBody(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<WebcastGiftMessageBody> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<WebcastGiftMessageBody> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int BODY_FIELD_NUMBER = 1;
    private com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody body_;
    /**
     * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody getBody() {
      return body_ == null ? com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.getDefaultInstance() : body_;
    }
    /**
     * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
     */
    @java.lang.Override
    public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (body_ != null) {
        output.writeMessage(1, getBody());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage)) {
        return super.equals(obj);
      }
      com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage other = (com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage) obj;

      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.douyin.webcast.proto.WebcastGiftMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.douyin.webcast.proto.WebcastGiftMessage)
        com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.class, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.Builder.class);
      }

      // Construct using com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.douyin.webcast.WebcastGiftMessageSerializer.internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor;
      }

      @java.lang.Override
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage getDefaultInstanceForType() {
        return com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage build() {
        com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage buildPartial() {
        com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage result = new com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage(this);
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage) {
          return mergeFrom((com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage other) {
        if (other == com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.getDefaultInstance()) return this;
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder> bodyBuilder_;
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       * @return The body.
       */
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      public Builder setBody(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      public Builder setBody(
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      public Builder mergeBody(com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.com.douyin.webcast.proto.WebcastGiftMessage.WebcastGiftMessageBody body = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBody.Builder, com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage.WebcastGiftMessageBodyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.douyin.webcast.proto.WebcastGiftMessage)
    }

    // @@protoc_insertion_point(class_scope:com.douyin.webcast.proto.WebcastGiftMessage)
    private static final com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage();
    }

    public static com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebcastGiftMessage>
        PARSER = new com.google.protobuf.AbstractParser<WebcastGiftMessage>() {
      @java.lang.Override
      public WebcastGiftMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WebcastGiftMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WebcastGiftMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebcastGiftMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.douyin.webcast.WebcastGiftMessageSerializer.WebcastGiftMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_WebcastGiftMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030WebcastGiftMessage.proto\022\030com.douyin.w" +
      "ebcast.proto\032\016TimeInfo.proto\032\016UserInfo.p" +
      "roto\032\025GiftDetailsInfo.proto\"\356\003\n\022WebcastG" +
      "iftMessage\022Q\n\004body\030\001 \001(\0132C.com.douyin.we" +
      "bcast.proto.WebcastGiftMessage.WebcastGi" +
      "ftMessageBody\032\204\003\n\026WebcastGiftMessageBody" +
      "\0224\n\010timeInfo\030\001 \001(\0132\".com.douyin.webcast." +
      "proto.TimeInfo\022\023\n\013gift_bofy_2\030\002 \001(\005\022\023\n\013g" +
      "ift_body_3\030\003 \001(\003\022\023\n\013gift_body_4\030\004 \001(\005\022\022\n" +
      "\ngift_count\030\005 \001(\005\022\023\n\013gift_body_6\030\006 \001(\005\0224" +
      "\n\010userInfo\030\007 \001(\0132\".com.douyin.webcast.pr" +
      "oto.UserInfo\022\023\n\013gift_body_9\030\t \001(\005\022\021\n\ttim" +
      "estamp\030\013 \001(\003\022\024\n\014gift_body_13\030\r \001(\005\022B\n\017gi" +
      "ftDetailsInfo\030\017 \001(\0132).com.douyin.webcast" +
      ".proto.GiftDetailsInfo\022\024\n\014gift_body_16\030\020" +
      " \001(\tB2\n\022com.douyin.webcastB\034WebcastGiftM" +
      "essageSerializerb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.douyin.webcast.TimeInfoSerializer.getDescriptor(),
          com.douyin.webcast.UserInfoSerializer.getDescriptor(),
          com.douyin.webcast.GiftDetailsInfoSerializer.getDescriptor(),
        });
    internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_douyin_webcast_proto_WebcastGiftMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor,
        new java.lang.String[] { "Body", });
    internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_descriptor =
      internal_static_com_douyin_webcast_proto_WebcastGiftMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_douyin_webcast_proto_WebcastGiftMessage_WebcastGiftMessageBody_descriptor,
        new java.lang.String[] { "TimeInfo", "GiftBofy2", "GiftBody3", "GiftBody4", "GiftCount", "GiftBody6", "UserInfo", "GiftBody9", "Timestamp", "GiftBody13", "GiftDetailsInfo", "GiftBody16", });
    com.douyin.webcast.TimeInfoSerializer.getDescriptor();
    com.douyin.webcast.UserInfoSerializer.getDescriptor();
    com.douyin.webcast.GiftDetailsInfoSerializer.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
